

"""
Code 14 Figure 2-19 Dinucleotide periodicity strength.py
=========================================================

WHAT THIS SCRIPT DOES
---------------------
Generates the data underlying Figure 2.19.

The analysis quantifies periodicity strength for all 16
dinucleotides.

For each dinucleotide and each group of sequences:

    1. The central 113-bp variable region is retained.

    2. A dinucleotide indicator trace of length 113 is constructed:

           1 = the dinucleotide starts at this position
           0 = otherwise

       There are 112 possible dinucleotide start positions.
       Positions 0-111 contain the dinucleotide indicators and
       the final element remains 0.

    3. The mean of each individual indicator trace is subtracted.

    4. A Hann window of length 113 is applied.

    5. The real FFT (rFFT) is calculated.

    6. Power is calculated as the squared magnitude of the FFT.

    7. Power is normalized by:

           L^2 * mean(Hann_window^2)

       where L = 113.

    8. The zero-frequency component is excluded.

    9. Individual power spectra are averaged.

       For the top-sequence analyses, all retained sequences
       contribute equally.

       For analyses across all reads, spectra are weighted by
       Counts Per Million.

   10. To quantify the periodic signal, the mean spectrum is
       restricted to periodicities between 5 and 20 bp.

   11. A smooth baseline is calculated using a
       Savitzky-Golay filter with:

           window length = 9
           polynomial order = 2

   12. The baseline is subtracted from the mean spectrum.

   13. The maximum baseline-corrected power between 5 and
       20 bp is recorded as the periodicity strength.


FIGURE 2.19 OUTPUTS
-------------------
Panel 1:
    Peak periodic power for all 16 dinucleotides among the
    most enriched sequences in each SELEX round.

Panel 2:
    Peak periodic power for all 16 dinucleotides across all
    reads in each SELEX round, weighted by Counts Per Million.

Panel 3:
    Comparison of peak periodic power between the most
    enriched Round 6 SELEX sequences and the top 10% of
    native yeast nucleosomes.


INPUT FILES
-----------
R1.csv
R2.csv
R3.csv
R4.csv
R5.csv
R6.csv

Each SELEX CSV must contain:

    Sequence
    Counts Per Million


VARIABLES THAT MUST ALREADY EXIST
---------------------------------
native_nucleosomes

Generated by:

    Code 5 Native yeast nucleosomal sequences.py

Expected columns:

    Sequence
    NCP_score


OTHER SCRIPTS THAT MUST BE RUN FIRST
------------------------------------
Code 5 Native yeast nucleosomal sequences.py


TOP-SEQUENCE FILTERING
----------------------
For each SELEX round, sequences are ranked by
Counts Per Million.

The top 10,000 sequences are initially selected.

Near-duplicate sequences differing at fewer than 10 positions
are removed, retaining the higher-abundance sequence.


OUTPUTS
-------
figure_2_19_top

    Long-format dataframe containing peak periodicity
    strength for the top sequences in R1-R6.

figure_2_19_all

    Long-format dataframe containing peak periodicity
    strength across all reads in R1-R6, CPM weighted.

figure_2_19_native_comparison

    Long-format dataframe comparing Round 6 with the
    top 10% of native yeast nucleosomes.

Wide-format versions of all three outputs are also generated.

No plotting is performed.
"""


import numpy as np
import pandas as pd

from itertools import product
from scipy.signal import savgol_filter


# ============================================================
# 1. Analysis settings
# ============================================================

ROUNDS = [
    "R1",
    "R2",
    "R3",
    "R4",
    "R5",
    "R6",
]


DINUCLEOTIDES = [

    "".join(x)

    for x in product(
        "ACGT",
        repeat=2
    )
]


TOP_N = 10_000

MIN_HAMMING_DISTANCE = 10


# Full SELEX sequence length.

RAW_LENGTH = 147


# 17 bp are removed from each end.

TRIM = 17


# Length of the central variable region and Fourier trace.

L = 113


# Range used to identify the periodic peak.

PEAK_PERIOD_MIN = 5.0

PEAK_PERIOD_MAX = 20.0


# Savitzky-Golay baseline parameters.

BASELINE_WINDOW_LENGTH = 9

BASELINE_POLYORDER = 2


# ============================================================
# 2. Load SELEX rounds
# ============================================================

round_data = {}


for rnd in ROUNDS:

    filename = f"{rnd}.csv"


    df = pd.read_csv(
        filename
    )


    required_columns = {
        "Sequence",
        "Counts Per Million",
    }


    missing_columns = (

        required_columns

        -

        set(
            df.columns
        )
    )


    if missing_columns:

        raise ValueError(
            f"{filename} is missing columns: "
            f"{missing_columns}"
        )


    df["Sequence"] = (

        df["Sequence"]

        .astype(str)

        .str.upper()
    )


    # Check sequence lengths.

    sequence_lengths = (
        df["Sequence"]
        .str.len()
    )


    if not (
        sequence_lengths == RAW_LENGTH
    ).all():

        bad_lengths = (

            sequence_lengths[
                sequence_lengths != RAW_LENGTH
            ]

            .value_counts()

            .to_dict()
        )


        raise ValueError(
            f"{filename} contains sequences that are not "
            f"147 bp long: {bad_lengths}"
        )


    round_data[
        rnd
    ] = df


# ============================================================
# 3. Hamming distance
# ============================================================

def hamming_distance(
    sequence_1,
    sequence_2
):

    """
    Number of positions at which two equal-length
    sequences differ.
    """

    return sum(

        base_1 != base_2

        for base_1, base_2
        in zip(
            sequence_1,
            sequence_2
        )
    )


# ============================================================
# 4. Select and filter top sequences
# ============================================================

def filter_top_sequences(
    dataframe,
    top_n=TOP_N,
    min_distance=MIN_HAMMING_DISTANCE
):

    """
    Rank sequences by Counts Per Million and initially
    select the top N.

    Sequences are processed from highest to lowest
    abundance.

    A sequence is retained only if it differs from every
    previously retained sequence at at least
    `min_distance` positions.
    """

    top = (

        dataframe

        .sort_values(
            "Counts Per Million",
            ascending=False
        )

        .head(
            top_n
        )

        .reset_index(
            drop=True
        )
    )


    retained_rows = []

    retained_sequences = []


    for _, row in top.iterrows():

        sequence = row[
            "Sequence"
        ]


        keep = True


        for previous_sequence in retained_sequences:

            if hamming_distance(
                sequence,
                previous_sequence
            ) < min_distance:

                keep = False

                break


        if keep:

            retained_rows.append(
                row
            )

            retained_sequences.append(
                sequence
            )


    return (

        pd.DataFrame(
            retained_rows
        )

        .reset_index(
            drop=True
        )
    )


# ============================================================
# 5. Generate filtered top-sequence sets
# ============================================================

top_sequences_by_round = {}


for rnd in ROUNDS:

    print(
        f"Filtering top sequences for {rnd}..."
    )


    filtered = filter_top_sequences(
        round_data[
            rnd
        ]
    )


    top_sequences_by_round[
        rnd
    ] = filtered


    print(
        rnd,
        "retained:",
        len(filtered)
    )


# The expected Round 6 result is 9,803 sequences.

if len(
    top_sequences_by_round[
        "R6"
    ]
) != 9803:

    print(
        "\nWARNING:"
        "\nThe Round 6 filtering did not produce exactly "
        "9,803 sequences."
        "\nCheck that R6.csv corresponds to the dataset "
        "used for this analysis."
    )


# ============================================================
# 6. Extract central 113-bp region
# ============================================================

def central_113(
    sequence
):

    """
    Extract positions 17:130 from a 147-bp sequence.
    """

    sequence = str(
        sequence
    ).upper()


    if len(
        sequence
    ) != RAW_LENGTH:

        raise ValueError(
            "Expected a 147-bp sequence, "
            f"but found length {len(sequence)}."
        )


    return sequence[
        TRIM:
        RAW_LENGTH - TRIM
    ]


# ============================================================
# 7. Construct dinucleotide indicator matrix
# ============================================================

def make_indicator_matrix(
    sequences,
    dinucleotide
):

    """
    Construct a matrix with one 113-element indicator
    trace per sequence.

    Positions 0-111 indicate whether the selected
    dinucleotide starts at that position.

    The final element remains zero.
    """

    N = len(
        sequences
    )


    indicator = np.zeros(
        (
            N,
            L
        ),
        dtype=np.float64
    )


    for sequence_index, sequence in enumerate(
        sequences
    ):

        sequence = central_113(
            sequence
        )


        for position in range(
            L - 1
        ):

            if (
                sequence[
                    position:
                    position + 2
                ]
                ==
                dinucleotide
            ):

                indicator[
                    sequence_index,
                    position
                ] = 1.0


    return indicator


# ============================================================
# 8. Calculate individual Fourier power spectra
# ============================================================

def calculate_power_spectra(
    sequences,
    dinucleotide
):

    """
    Calculate normalized Fourier power spectra for all
    sequences for one dinucleotide.
    """

    indicator = make_indicator_matrix(
        sequences,
        dinucleotide
    )


    # Mean-centre every sequence independently.

    centered = (

        indicator

        -

        indicator.mean(
            axis=1,
            keepdims=True
        )
    )


    # Hann window.

    hann_window = np.hanning(
        L
    ).astype(
        np.float64
    )


    window_power_correction = np.mean(
        hann_window ** 2
    )


    windowed = (

        centered

        *

        hann_window[
            None,
            :
        ]
    )


    # Real Fourier transform.

    fft_values = np.fft.rfft(
        windowed,
        axis=1
    )


    # Normalized power.

    power = (

        np.abs(
            fft_values
        ) ** 2

        /

        (
            L ** 2
            *
            window_power_correction
        )
    )


    # Exclude zero frequency.

    frequency_indices = np.arange(
        power.shape[1]
    )


    keep = (
        frequency_indices
        >
        0
    )


    frequency_indices = (
        frequency_indices[
            keep
        ]
    )


    periodicity = (

        L

        /

        frequency_indices
    )


    power = (
        power[
            :,
            keep
        ]
    )


    return (
        periodicity,
        power
    )


# ============================================================
# 9. Calculate mean power spectrum
# ============================================================

def mean_power_spectrum(
    sequences,
    dinucleotide,
    weights=None
):

    """
    Calculate the mean Fourier power spectrum.

    If weights is None, every sequence contributes equally.

    If weights are supplied, spectra are averaged using
    those weights.
    """

    periodicity, power = (
        calculate_power_spectra(
            sequences,
            dinucleotide
        )
    )


    if weights is None:

        mean_power = np.mean(
            power,
            axis=0
        )


    else:

        weights = np.asarray(
            weights,
            dtype=np.float64
        )


        if len(
            weights
        ) != len(
            sequences
        ):

            raise ValueError(
                "Number of weights does not match "
                "number of sequences."
            )


        mean_power = np.average(
            power,
            axis=0,
            weights=weights
        )


    return (
        periodicity,
        mean_power
    )


# ============================================================
# 10. Baseline correction and peak extraction
# ============================================================

def periodicity_peak(
    periodicity,
    mean_power
):

    """
    Restrict the spectrum to periodicities between
    5 and 20 bp.

    Calculate a Savitzky-Golay baseline and subtract it.

    Return the maximum baseline-corrected power and the
    periodicity at which that maximum occurs.
    """

    mask = (

        (periodicity >= PEAK_PERIOD_MIN)

        &

        (periodicity <= PEAK_PERIOD_MAX)
    )


    periodicity_selected = (
        periodicity[
            mask
        ]
    )


    power_selected = (
        mean_power[
            mask
        ]
    )


    if len(
        power_selected
    ) < BASELINE_WINDOW_LENGTH:

        raise ValueError(
            "Not enough Fourier points are present "
            "for the Savitzky-Golay baseline."
        )


    baseline = savgol_filter(

        power_selected,

        window_length=
            BASELINE_WINDOW_LENGTH,

        polyorder=
            BASELINE_POLYORDER
    )


    corrected_power = (

        power_selected

        -

        baseline
    )


    peak_index = np.argmax(
        corrected_power
    )


    peak_power = (
        corrected_power[
            peak_index
        ]
    )


    peak_periodicity = (
        periodicity_selected[
            peak_index
        ]
    )


    return (
        peak_power,
        peak_periodicity
    )


# ============================================================
# 11. Panel 1:
#     top enriched sequences in each SELEX round
# ============================================================

top_peak_rows = []


for rnd in ROUNDS:

    print(
        f"\nTop sequences: {rnd}"
    )


    df_top = (
        top_sequences_by_round[
            rnd
        ]
    )


    sequences = (
        df_top[
            "Sequence"
        ]
        .tolist()
    )


    for dinucleotide in DINUCLEOTIDES:

        print(
            rnd,
            dinucleotide
        )


        periodicity, mean_power = (
            mean_power_spectrum(
                sequences,
                dinucleotide
            )
        )


        peak_power, peak_periodicity = (
            periodicity_peak(
                periodicity,
                mean_power
            )
        )


        top_peak_rows.append({

            "Round":
                rnd,

            "Dinucleotide":
                dinucleotide,

            "N_sequences":
                len(sequences),

            "Peak_periodicity_bp":
                peak_periodicity,

            "Peak_power":
                peak_power,
        })


figure_2_19_top = pd.DataFrame(
    top_peak_rows
)


# ============================================================
# 12. Panel 2:
#     all reads, CPM weighted
# ============================================================

all_peak_rows = []


for rnd in ROUNDS:

    print(
        f"\nAll reads: {rnd}"
    )


    df_round = (
        round_data[
            rnd
        ]
    )


    sequences = (
        df_round[
            "Sequence"
        ]
        .tolist()
    )


    weights = (

        df_round[
            "Counts Per Million"
        ]

        .to_numpy(
            dtype=np.float64
        )
    )


    for dinucleotide in DINUCLEOTIDES:

        print(
            rnd,
            dinucleotide
        )


        periodicity, mean_power = (
            mean_power_spectrum(
                sequences,
                dinucleotide,
                weights=weights
            )
        )


        peak_power, peak_periodicity = (
            periodicity_peak(
                periodicity,
                mean_power
            )
        )


        all_peak_rows.append({

            "Round":
                rnd,

            "Dinucleotide":
                dinucleotide,

            "N_unique_sequences":
                len(sequences),

            "Peak_periodicity_bp":
                peak_periodicity,

            "Peak_power":
                peak_power,
        })


figure_2_19_all = pd.DataFrame(
    all_peak_rows
)


# ============================================================
# 13. Select top 10% native yeast nucleosomes
# ============================================================

if "native_nucleosomes" not in globals():

    raise RuntimeError(
        "native_nucleosomes is not defined. "
        "Run 'Code 5 Native yeast nucleosomal sequences.py' "
        "before this script."
    )


required_native_columns = {
    "Sequence",
    "NCP_score",
}


missing_native_columns = (

    required_native_columns

    -

    set(
        native_nucleosomes.columns
    )
)


if missing_native_columns:

    raise ValueError(
        "native_nucleosomes is missing columns: "
        f"{missing_native_columns}"
    )


native_sorted = (

    native_nucleosomes

    .sort_values(
        "NCP_score",
        ascending=False
    )

    .reset_index(
        drop=True
    )
)


n_top_native = int(
    np.ceil(
        0.10
        *
        len(
            native_sorted
        )
    )
)


top_native = (

    native_sorted

    .head(
        n_top_native
    )

    .copy()
)


print(
    "\nNative nucleosomes:",
    len(native_sorted)
)


print(
    "Top 10% native nucleosomes:",
    len(top_native)
)


# ============================================================
# 14. Panel 3:
#     Round 6 versus top 10% native yeast
# ============================================================

r6_sequences = (

    top_sequences_by_round[
        "R6"
    ][
        "Sequence"
    ]

    .tolist()
)


native_sequences = (

    top_native[
        "Sequence"
    ]

    .astype(str)

    .str.upper()

    .tolist()
)


comparison_rows = []


for dinucleotide in DINUCLEOTIDES:

    print(
        "\nR6 versus native:",
        dinucleotide
    )


    # --------------------------------------------------------
    # Round 6
    # --------------------------------------------------------

    periodicity_r6, mean_power_r6 = (
        mean_power_spectrum(
            r6_sequences,
            dinucleotide
        )
    )


    r6_peak_power, r6_peak_periodicity = (
        periodicity_peak(
            periodicity_r6,
            mean_power_r6
        )
    )


    comparison_rows.append({

        "Dataset":
            "R6_top",

        "Dinucleotide":
            dinucleotide,

        "N_sequences":
            len(
                r6_sequences
            ),

        "Peak_periodicity_bp":
            r6_peak_periodicity,

        "Peak_power":
            r6_peak_power,
    })


    # --------------------------------------------------------
    # Top 10% native yeast nucleosomes
    # --------------------------------------------------------

    periodicity_native, mean_power_native = (
        mean_power_spectrum(
            native_sequences,
            dinucleotide
        )
    )


    (
        native_peak_power,
        native_peak_periodicity

    ) = periodicity_peak(

        periodicity_native,
        mean_power_native
    )


    comparison_rows.append({

        "Dataset":
            "Top_10_percent_yeast",

        "Dinucleotide":
            dinucleotide,

        "N_sequences":
            len(
                native_sequences
            ),

        "Peak_periodicity_bp":
            native_peak_periodicity,

        "Peak_power":
            native_peak_power,
    })


figure_2_19_native_comparison = (
    pd.DataFrame(
        comparison_rows
    )
)


# ============================================================
# 15. Wide-format output tables
# ============================================================

figure_2_19_top_wide = (

    figure_2_19_top

    .pivot(
        index="Dinucleotide",
        columns="Round",
        values="Peak_power"
    )

    .reset_index()
)


figure_2_19_all_wide = (

    figure_2_19_all

    .pivot(
        index="Dinucleotide",
        columns="Round",
        values="Peak_power"
    )

    .reset_index()
)


figure_2_19_native_comparison_wide = (

    figure_2_19_native_comparison

    .pivot(
        index="Dinucleotide",
        columns="Dataset",
        values="Peak_power"
    )

    .reset_index()
)


# ============================================================
# OUTPUT SUMMARY
# ============================================================

# Panel 1:
#
#     figure_2_19_top
#     figure_2_19_top_wide
#
# Maximum baseline-corrected power between 5 and 20 bp
# for all 16 dinucleotides among the filtered top
# sequences in R1-R6.
#
#
# Panel 2:
#
#     figure_2_19_all
#     figure_2_19_all_wide
#
# Maximum baseline-corrected power between 5 and 20 bp
# for all 16 dinucleotides across all reads in R1-R6,
# weighted by Counts Per Million.
#
#
# Panel 3:
#
#     figure_2_19_native_comparison
#     figure_2_19_native_comparison_wide
#
# Maximum baseline-corrected power between 5 and 20 bp
# comparing the filtered top Round 6 sequences with the
# top 10% of native yeast nucleosomes.
#
#
# Baseline correction:
#
#     Savitzky-Golay filter
#     window_length = 9
#     polyorder     = 2
#
#
# No plotting is performed.