

"""
SCRIPT NAME:
Code 35 Figure 3-15b occupancy around plus-one nucleosomes.py


WHAT THIS SCRIPT DOES:
Reconstructs Figure 3.15b.

For each transcript in Pugh.txt:

1. Uses Experiment_Left and Experiment_Right to define the
   transcript-associated genomic interval.

2. Finds all experimentally mapped native nucleosome dyads from
   the SacCer3 nucleosome map that fall within this interval.

3. Orders those nucleosomes in the direction of transcription.
   For minus-strand transcripts, the genomic list is reversed.

4. Defines the FIRST nucleosome in transcriptional order as the
   +1 nucleosome.

5. Aligns:
       a) measured in-vitro nucleosome occupancy
       b) predicted occupancy from the 10-mer cumulative-score
          + hard-rod model
   around this independently identified +1 dyad.

6. Reverses profiles for minus-strand transcripts so that all
   genes have the same transcriptional orientation.

7. Calculates mean occupancy and SEM as a function of distance
   from the +1 nucleosome dyad.

No plotting is performed.


THESIS SECTION / FIGURE:
Figure 3.15b


INPUT FILES:

1. Pugh.txt

   Transcript annotation from:

   Rossi MJ et al. (2021)
   A high-resolution protein architecture of the budding yeast genome.
   Nature 592, 309-314.
   DOI: 10.1038/s41586-021-03314-8

   Required columns:
       Systematic ID
       Feature class Level 1
       Chrom
       Strand
       Experiment_Left
       Experiment_Right

   IMPORTANT:
   The PlusOne_Dyad column in Pugh.txt is NOT used.


2. Saccer3bed.bed

   SacCer3 version of the native yeast nucleosome map.

   This is generated by:

       NucleosomeSacCer2.txt
           ->
       SacCer2bed.bed
           ->
       UCSC liftOver using sacCer2ToSacCer3.over.chain.gz
           ->
       Saccer3bed.bed

   Each BED interval corresponds to a nucleosome centred at:

       Start + 10

   This is the same SacCer3 nucleosome map used in
   Code 5 Native yeast nucleosomal sequences.py.


VARIABLES THAT MUST ALREADY EXIST:

zhang_occ

    Dictionary from Code 34 / Figure 3.15a:

        zhang_occ["chr1"]
        ...
        zhang_occ["chr16"]

    Each array contains measured Kaplan et al. in-vitro
    nucleosome occupancy at genomic positions.


yeast_pred_occ

    Dictionary from Code 34 / Figure 3.15a:

        yeast_pred_occ["chr1"]
        ...
        yeast_pred_occ["chr16"]

    Each array contains predicted occupancy from the
    108-bp 10-mer cumulative score + hard-rod model.


OTHER SCRIPTS THAT MUST BE RUN FIRST:

Code 34 Figure 3-15 genome-wide nucleosome occupancy.py


OUTPUT VARIABLES:

df3
    SacCer3 native nucleosome dyad table.

df6
    Transcript table containing native nucleosome centers in
    transcriptional order.

plus1_table
    Transcripts for which an independently identified +1
    nucleosome was available.

measured_plus1_profiles
    Individual measured occupancy profiles around +1 dyads.

predicted_plus1_profiles
    Individual predicted occupancy profiles around +1 dyads.

figure_3_15b
    Mean +/- SEM data required for plotting Figure 3.15b.


IMPORTANT DEFINITION OF THE +1 NUCLEOSOME:

The +1 nucleosome is NOT taken from the PlusOne_Dyad column
of Pugh.txt.

Instead:

    + strand:
        +1 = leftmost native nucleosome within the experimental
             transcript interval

    - strand:
        +1 = rightmost native nucleosome within the experimental
             transcript interval

This is implemented by collecting nucleosomes in genomic order
and reversing the list for minus-strand transcripts.

The first item in the resulting transcription-oriented list is
therefore the +1 nucleosome.
"""


import numpy as np
import pandas as pd


# ================================================================
# 1. Constants
# ================================================================

PUGH_FILE = "Pugh.txt"

SACCER3_NUCLEOSOME_BED = "Saccer3bed.bed"


# Window around the independently identified +1 nucleosome.
#
# Produces:
#
#     -1000 ... 0 ... +1000
#
# where zero is the +1 nucleosome dyad.

PLUS1_WINDOW = 1000


relative_positions = np.arange(
    -PLUS1_WINDOW,
    PLUS1_WINDOW + 1
)


# ================================================================
# 2. Roman chromosome conversion
# ================================================================
#
# Saccer3bed.bed generated by liftOver may contain chromosome
# identifiers such as:
#
#     chrI
#     chrII
#     ...
#     chrXVI
#
# Pugh.txt uses:
#
#     chr1
#     chr2
#     ...
#     chr16
#
# Convert the lifted nucleosome map to the latter convention.
# ================================================================

ROMAN_TO_ARABIC = {
    "I": 1,
    "II": 2,
    "III": 3,
    "IV": 4,
    "V": 5,
    "VI": 6,
    "VII": 7,
    "VIII": 8,
    "IX": 9,
    "X": 10,
    "XI": 11,
    "XII": 12,
    "XIII": 13,
    "XIV": 14,
    "XV": 15,
    "XVI": 16
}


def convert_roman_to_arabic(chromosome):
    """
    Convert chromosome identifiers to the form chr1 ... chr16.

    Examples
    --------
    chrI    -> chr1
    chrIV   -> chr4
    chrXVI  -> chr16

    Already numeric identifiers such as chr4 are left in the same
    convention.
    """

    chromosome = str(chromosome).strip()

    if chromosome.lower().startswith("chr"):
        chromosome_part = chromosome[3:]
    else:
        chromosome_part = chromosome


    # Already Arabic.
    if chromosome_part.isdigit():

        return f"chr{int(chromosome_part)}"


    chromosome_part = chromosome_part.upper()

    if chromosome_part not in ROMAN_TO_ARABIC:

        raise ValueError(
            "Unrecognised chromosome identifier: "
            + str(chromosome)
        )


    return (
        "chr"
        +
        str(ROMAN_TO_ARABIC[chromosome_part])
    )


# ================================================================
# 3. Load the SacCer3 native nucleosome map
# ================================================================
#
# This is the liftOver product used in Code 5.
#
# Each interval was originally constructed as:
#
#     Start = original dyad - 10
#     End   = original dyad + 10
#
# Therefore, after liftOver:
#
#     Dyad = Start + 10
#
# This reproduces the construction used previously.
# ================================================================

df3 = pd.read_csv(
    SACCER3_NUCLEOSOME_BED,
    sep="\t",
    header=None,
    names=[
        "Chromosome",
        "Start",
        "End"
    ]
)


df3["Dyad"] = (
    df3["Start"]
    +
    10
)


df3 = df3[
    [
        "Chromosome",
        "Dyad"
    ]
].copy()


# Convert chromosome names to chr1 ... chr16.

df3["Chromosome"] = (
    df3["Chromosome"]
    .apply(convert_roman_to_arabic)
)


# Ensure integer dyad coordinates.

df3["Dyad"] = (
    pd.to_numeric(
        df3["Dyad"],
        errors="coerce"
    )
)


df3 = df3[
    df3["Dyad"].notna()
].copy()


df3["Dyad"] = (
    df3["Dyad"]
    .astype(int)
)


# Sort explicitly by genomic coordinate.
#
# This is important because the first nucleosome will subsequently
# be interpreted according to transcriptional orientation.

df3 = (
    df3
    .sort_values(
        [
            "Chromosome",
            "Dyad"
        ]
    )
    .reset_index(drop=True)
)


print(
    "Number of SacCer3 native nucleosomes:",
    len(df3)
)


# ================================================================
# 4. Load Pugh transcript annotation
# ================================================================

df4 = pd.read_csv(
    PUGH_FILE,
    sep="\t"
)


required_columns = {
    "Systematic ID",
    "Feature class Level 1",
    "Chrom",
    "Strand",
    "Experiment_Left",
    "Experiment_Right"
}


missing_columns = (
    required_columns
    -
    set(df4.columns)
)


if missing_columns:

    raise ValueError(
        "Pugh.txt is missing required columns: "
        +
        ", ".join(sorted(missing_columns))
    )


# ================================================================
# 5. Construct df5
# ================================================================
#
# This follows the previous code.
#
# Note that PlusOne_Dyad is deliberately NOT included.
# ================================================================

df5 = df4[
    [
        "Systematic ID",
        "Feature class Level 1",
        "Chrom",
        "Strand",
        "Experiment_Left",
        "Experiment_Right"
    ]
].copy()


# ================================================================
# 6. Construct df6
# ================================================================
#
# IMPORTANT:
#
# The old exploratory code contained:
#
# df6 = df5[
#     df5["Feature class Level 1"]
#     .str[:2]
#     .isin(["01", "02", "03", "04"])
# ]
#
# That restriction is NOT part of the actual analysis.
#
# Everything with a non-NA Feature class Level 1 is considered.
# ================================================================

df6 = df5[
    ~df5["Feature class Level 1"].isna()
].copy()


# We also need usable chromosome, strand and interval coordinates.

df6 = df6[
    df6["Chrom"].notna()
    &
    df6["Strand"].notna()
    &
    df6["Experiment_Left"].notna()
    &
    df6["Experiment_Right"].notna()
].copy()


df6 = df6[
    df6["Strand"].isin(
        ["+", "-"]
    )
].copy()


# ================================================================
# 7. Standardise chromosome identifiers in Pugh data
# ================================================================

df6["Chrom"] = (
    df6["Chrom"]
    .apply(convert_roman_to_arabic)
)


# ================================================================
# 8. Convert experimental transcript boundaries to integers
# ================================================================

df6["Experiment_Left"] = pd.to_numeric(
    df6["Experiment_Left"],
    errors="coerce"
)


df6["Experiment_Right"] = pd.to_numeric(
    df6["Experiment_Right"],
    errors="coerce"
)


df6 = df6[
    df6["Experiment_Left"].notna()
    &
    df6["Experiment_Right"].notna()
].copy()


df6["Experiment_Left"] = (
    df6["Experiment_Left"]
    .astype(int)
)


df6["Experiment_Right"] = (
    df6["Experiment_Right"]
    .astype(int)
)


# ================================================================
# 9. Find all native nucleosomes belonging to each transcript
# ================================================================
#
# A native nucleosome is associated with a transcript if its
# SacCer3 dyad lies between:
#
#     Experiment_Left
#
# and:
#
#     Experiment_Right
#
# inclusive.
#
# df3 has already been sorted in increasing genomic-coordinate
# order.
# ================================================================

def get_nucleosome_centers(row):

    chrom = row["Chrom"]

    left = row["Experiment_Left"]

    right = row["Experiment_Right"]


    nucleosome_centers = (
        df3.loc[
            (df3["Chromosome"] == chrom)
            &
            (df3["Dyad"] >= left)
            &
            (df3["Dyad"] <= right),
            "Dyad"
        ]
        .tolist()
    )


    return nucleosome_centers


df6["Nucleosome centers"] = (
    df6.apply(
        get_nucleosome_centers,
        axis=1
    )
)


# ================================================================
# 10. Put nucleosome lists into transcriptional orientation
# ================================================================
#
# PLUS strand:
#
#     transcription proceeds toward increasing genomic coordinate
#
#     [leftmost, ..., rightmost]
#
#
# MINUS strand:
#
#     transcription proceeds toward decreasing genomic coordinate
#
# so reverse:
#
#     [rightmost, ..., leftmost]
#
#
# After this operation, element [0] is the first nucleosome
# encountered in the direction of transcription.
# ================================================================

minus_mask = (
    df6["Strand"]
    ==
    "-"
)


df6.loc[
    minus_mask,
    "Nucleosome centers"
] = (
    df6.loc[
        minus_mask,
        "Nucleosome centers"
    ]
    .apply(
        lambda x: x[::-1]
    )
)


# ================================================================
# 11. Define the +1 nucleosome
# ================================================================
#
# Do NOT use:
#
#     df4["PlusOne_Dyad"]
#
# The +1 dyad is independently obtained from the SacCer3 native
# nucleosome map.
#
# Because Nucleosome centers is now in transcriptional order:
#
#     Nucleosome centers[0]
#
# is the +1 nucleosome.
# ================================================================

df6["Number of nucleosomes"] = (
    df6["Nucleosome centers"]
    .apply(len)
)


# Keep transcripts for which at least one native nucleosome was
# identified within the experimental transcript interval.

plus1_table = df6[
    df6["Number of nucleosomes"] > 0
].copy()


plus1_table["Plus1_Dyad_from_native_map"] = (
    plus1_table[
        "Nucleosome centers"
    ]
    .apply(
        lambda x: x[0]
    )
)


plus1_table[
    "Plus1_Dyad_from_native_map"
] = (
    plus1_table[
        "Plus1_Dyad_from_native_map"
    ]
    .astype(int)
)


print()
print(
    "Transcripts considered:",
    len(df6)
)

print(
    "Transcripts with >= 1 mapped native nucleosome:",
    len(plus1_table)
)


# ================================================================
# 12. Check the occupancy dictionaries from Figure 3.15a
# ================================================================

expected_chromosomes = {
    f"chr{i}"
    for i in range(1, 17)
}


missing_predicted = (
    expected_chromosomes
    -
    set(yeast_pred_occ.keys())
)


missing_measured = (
    expected_chromosomes
    -
    set(zhang_occ.keys())
)


if missing_predicted:

    raise ValueError(
        "yeast_pred_occ is missing: "
        +
        ", ".join(
            sorted(missing_predicted)
        )
    )


if missing_measured:

    raise ValueError(
        "zhang_occ is missing: "
        +
        ", ".join(
            sorted(missing_measured)
        )
    )


# ================================================================
# 13. Extract occupancy around each independently identified
#     +1 nucleosome
# ================================================================
#
# IMPORTANT COORDINATE CONVENTION
#
# The SacCer3 dyad coordinate comes from the BED/liftOver
# construction:
#
#     Dyad = Start + 10
#
# BED coordinates are 0-based.
#
# Therefore these dyad coordinates are used DIRECTLY as Python
# array indices.
#
# There is NO "-1" conversion here.
#
# This differs from the Zhang occupancy input file, where the
# historic loader explicitly converted its input position using:
#
#     pos = int(pos) - 1
#
# By the time this section is run, zhang_occ itself is already a
# 0-based Python array.
# ================================================================

measured_plus1_profiles = []

predicted_plus1_profiles = []

metadata_rows = []


for row_index, row in plus1_table.iterrows():

    chrom = row["Chrom"]

    strand = row["Strand"]

    dyad_index = int(
        row[
            "Plus1_Dyad_from_native_map"
        ]
    )


    # ------------------------------------------------------------
    # Retrieve chromosome occupancy arrays
    # ------------------------------------------------------------

    measured_chrom = np.asarray(
        zhang_occ[chrom],
        dtype=float
    )


    predicted_chrom = np.asarray(
        yeast_pred_occ[chrom],
        dtype=float
    )


    # Both arrays should refer to the same chromosome.

    if (
        len(measured_chrom)
        !=
        len(predicted_chrom)
    ):

        raise ValueError(
            f"Occupancy-array length mismatch for {chrom}: "
            f"measured={len(measured_chrom)}, "
            f"predicted={len(predicted_chrom)}"
        )


    # ------------------------------------------------------------
    # Genomic interval around +1 dyad
    # ------------------------------------------------------------

    start = (
        dyad_index
        -
        PLUS1_WINDOW
    )


    end = (
        dyad_index
        +
        PLUS1_WINDOW
        +
        1
    )


    # ------------------------------------------------------------
    # Exclude dyads too close to chromosome ends
    # ------------------------------------------------------------

    if start < 0:
        continue


    if end > len(measured_chrom):
        continue


    # ------------------------------------------------------------
    # Extract measured occupancy
    # ------------------------------------------------------------

    measured_profile = (
        measured_chrom[
            start:end
        ]
        .copy()
    )


    # ------------------------------------------------------------
    # Extract predicted occupancy
    # ------------------------------------------------------------

    predicted_profile = (
        predicted_chrom[
            start:end
        ]
        .copy()
    )


    expected_length = (
        2 * PLUS1_WINDOW
        +
        1
    )


    if (
        len(measured_profile)
        !=
        expected_length
    ):
        continue


    if (
        len(predicted_profile)
        !=
        expected_length
    ):
        continue


    # ============================================================
    # 14. Orient every profile in the direction of transcription
    # ============================================================
    #
    # For a plus-strand transcript:
    #
    #     genomic left = upstream
    #     genomic right = downstream
    #
    # so nothing changes.
    #
    #
    # For a minus-strand transcript:
    #
    #     genomic right = upstream
    #     genomic left  = downstream
    #
    # so reverse the profile.
    #
    #
    # After this:
    #
    #     negative x = upstream / promoter
    #     zero       = +1 dyad
    #     positive x = downstream / gene body
    # ============================================================

    if strand == "-":

        measured_profile = (
            measured_profile[::-1]
        )

        predicted_profile = (
            predicted_profile[::-1]
        )


    # ------------------------------------------------------------
    # Store profile
    # ------------------------------------------------------------

    measured_plus1_profiles.append(
        measured_profile
    )


    predicted_plus1_profiles.append(
        predicted_profile
    )


    metadata_rows.append(
        {
            "original_df6_index":
                row_index,

            "Systematic ID":
                row["Systematic ID"],

            "Chrom":
                chrom,

            "Strand":
                strand,

            "Experiment_Left":
                row["Experiment_Left"],

            "Experiment_Right":
                row["Experiment_Right"],

            "Number of nucleosomes":
                row["Number of nucleosomes"],

            "Plus1_Dyad_from_native_map":
                dyad_index
        }
    )


# ================================================================
# 15. Convert profiles to matrices
# ================================================================

measured_plus1_profiles = np.asarray(
    measured_plus1_profiles,
    dtype=float
)


predicted_plus1_profiles = np.asarray(
    predicted_plus1_profiles,
    dtype=float
)


plus1_metadata = pd.DataFrame(
    metadata_rows
)


# ================================================================
# 16. Sanity checks
# ================================================================

expected_profile_length = (
    2 * PLUS1_WINDOW
    +
    1
)


if len(measured_plus1_profiles) == 0:

    raise ValueError(
        "No usable +1 nucleosome profiles were obtained."
    )


assert (
    measured_plus1_profiles.shape[1]
    ==
    expected_profile_length
)


assert (
    predicted_plus1_profiles.shape[1]
    ==
    expected_profile_length
)


assert (
    measured_plus1_profiles.shape[0]
    ==
    predicted_plus1_profiles.shape[0]
)


assert (
    measured_plus1_profiles.shape[0]
    ==
    len(plus1_metadata)
)


print()
print(
    "Number of profiles entering Figure 3.15b:",
    len(plus1_metadata)
)


print(
    "Measured matrix:",
    measured_plus1_profiles.shape
)


print(
    "Predicted matrix:",
    predicted_plus1_profiles.shape
)


# ================================================================
# 17. Calculate mean profiles
# ================================================================

measured_mean = np.nanmean(
    measured_plus1_profiles,
    axis=0
)


predicted_mean = np.nanmean(
    predicted_plus1_profiles,
    axis=0
)


# ================================================================
# 18. Calculate SEM
# ================================================================
#
# SEM at each relative position:
#
#     standard deviation / sqrt(N)
#
# Finite values only.
# ================================================================

def calculate_nansem(matrix):

    n = np.sum(
        np.isfinite(matrix),
        axis=0
    )


    sd = np.nanstd(
        matrix,
        axis=0,
        ddof=1
    )


    sem = (
        sd
        /
        np.sqrt(n)
    )


    return sem, n


measured_sem, measured_n = (
    calculate_nansem(
        measured_plus1_profiles
    )
)


predicted_sem, predicted_n = (
    calculate_nansem(
        predicted_plus1_profiles
    )
)


# ================================================================
# 19. Assemble Figure 3.15b data
# ================================================================
#
# This is the dataframe to use for plotting.
# ================================================================

figure_3_15b = pd.DataFrame(
    {
        "position_relative_to_plus1_dyad":
            relative_positions,

        "measured_mean":
            measured_mean,

        "measured_sem":
            measured_sem,

        "measured_n":
            measured_n,

        "predicted_mean":
            predicted_mean,

        "predicted_sem":
            predicted_sem,

        "predicted_n":
            predicted_n
    }
)


# ================================================================
# 20. Mean +/- SEM boundaries
# ================================================================

figure_3_15b[
    "measured_lower"
] = (
    figure_3_15b[
        "measured_mean"
    ]
    -
    figure_3_15b[
        "measured_sem"
    ]
)


figure_3_15b[
    "measured_upper"
] = (
    figure_3_15b[
        "measured_mean"
    ]
    +
    figure_3_15b[
        "measured_sem"
    ]
)


figure_3_15b[
    "predicted_lower"
] = (
    figure_3_15b[
        "predicted_mean"
    ]
    -
    figure_3_15b[
        "predicted_sem"
    ]
)


figure_3_15b[
    "predicted_upper"
] = (
    figure_3_15b[
        "predicted_mean"
    ]
    +
    figure_3_15b[
        "predicted_sem"
    ]
)


# ================================================================
# 21. Final checks
# ================================================================

assert (
    len(figure_3_15b)
    ==
    expected_profile_length
)


# Middle row must be the independently determined +1 dyad.

assert (
    figure_3_15b[
        "position_relative_to_plus1_dyad"
    ].iloc[PLUS1_WINDOW]
    ==
    0
)


print()
print(
    "Figure 3.15b data ready."
)


print(
    "Relative coordinate range:",
    relative_positions[0],
    "to",
    relative_positions[-1],
    "bp"
)


print()
print(
    figure_3_15b.head()
)


print()
print(
    "Position of +1 dyad in output dataframe:",
    figure_3_15b.iloc[
        PLUS1_WINDOW
    ][
        "position_relative_to_plus1_dyad"
    ]
)