

"""
Code 18 Figure 2-23 HRI across SELEX rounds.py
===============================================

WHAT THIS SCRIPT DOES
---------------------
Generates the data underlying Figure 2.23.

For each of the six SELEX rounds:

    1. Select the 10,000 sequences with the highest
       Counts Per Million.

    2. Remove near-duplicate sequences differing at
       fewer than 10 positions, retaining the more
       abundant sequence.

    3. Calculate the Helical Repetition Index (HRI)
       matrix for all 136 unordered NN-NN pairs.

Figure 2.23a consists of the six resulting HRI matrices.

For Figure 2.23b, three cumulative HRI signals are
calculated from each matrix:

    WW-WW:
        sum of the 10 independent HRI values formed
        by the four WW dinucleotides

    SS-SS:
        sum of the 10 independent HRI values formed
        by the four SS dinucleotides

    WW-SS:
        sum of all 16 HRI values formed by one WW
        and one SS dinucleotide

The three trajectories are also normalized relative to
their respective Round 6 magnitudes.


WW AND SS DEFINITIONS
---------------------
WW:

    AA
    AT
    TA
    TT

SS:

    CC
    CG
    GC
    GG


INPUT FILES
-----------
R1.csv
R2.csv
R3.csv
R4.csv
R5.csv
R6.csv

Each file must contain:

    Sequence
    Counts Per Million


VARIABLES / FUNCTIONS THAT MUST ALREADY EXIST
---------------------------------------------
The following functions and variables are generated by:

    Code 17 Figure 2-22 HRI heatmaps.py

Required:

    filter_top_sequences
    compute_hri_matrix
    DINUCLEOTIDE_ORDER


OTHER SCRIPTS THAT MUST BE RUN FIRST
------------------------------------
Code 17 Figure 2-22 HRI heatmaps.py


OUTPUTS
-------
HRI_by_round

    Dictionary containing the labelled 16 x 16 HRI
    matrix for each SELEX round.


figure_2_23a

    Long-format DataFrame containing the HRI matrices
    for all six rounds.


figure_2_23b

    DataFrame containing:

        Round
        WW_WW
        SS_SS
        WW_SS
        WW_WW_normalized
        SS_SS_normalized
        WW_SS_normalized


No plotting is performed.
"""


import numpy as np
import pandas as pd


# ============================================================
# 1. Input files
# ============================================================

ROUND_FILES = {

    1: "R1.csv",

    2: "R2.csv",

    3: "R3.csv",

    4: "R4.csv",

    5: "R5.csv",

    6: "R6.csv",
}


# ============================================================
# 2. Sequence-selection settings
# ============================================================

TOP_N = 10_000

MIN_HAMMING_DISTANCE = 10


# ============================================================
# 3. WW and SS dinucleotides
# ============================================================

WW = [

    "AA",
    "AT",
    "TA",
    "TT",
]


SS = [

    "CC",
    "CG",
    "GC",
    "GG",
]


# ============================================================
# 4. Check required functions and variables
# ============================================================

required_objects = [

    "filter_top_sequences",

    "compute_hri_matrix",

    "DINUCLEOTIDE_ORDER",
]


for required_object in required_objects:

    if required_object not in globals():

        raise RuntimeError(

            f"{required_object} is not defined. "

            "Run "
            "'Code 17 Figure 2-22 HRI heatmaps.py' "
            "before this script."
        )


# ============================================================
# 5. Load one SELEX round
# ============================================================

def load_round(
    filename
):

    """
    Load one SELEX CSV and check the required columns.
    """

    dataframe = pd.read_csv(
        filename
    )


    required_columns = {

        "Sequence",

        "Counts Per Million",
    }


    missing_columns = (

        required_columns

        -

        set(
            dataframe.columns
        )
    )


    if missing_columns:

        raise ValueError(

            f"{filename} is missing columns: "
            f"{missing_columns}"
        )


    dataframe[
        "Sequence"
    ] = (

        dataframe[
            "Sequence"
        ]

        .astype(str)

        .str.upper()
    )


    return dataframe


# ============================================================
# 6. Calculate the HRI matrix for every round
# ============================================================

HRI_by_round = {}

rho_by_round = {}

top_sequences_by_round = {}

n_sequences_by_round = {}


for round_number in range(
    1,
    7
):

    print(
        "\n"
        +
        "=" * 60
    )

    print(
        f"Round {round_number}"
    )

    print(
        "=" * 60
    )


    # --------------------------------------------------------
    # Load round
    # --------------------------------------------------------

    dataframe = load_round(

        ROUND_FILES[
            round_number
        ]
    )


    # --------------------------------------------------------
    # Select top 10,000 and remove near-duplicates
    # --------------------------------------------------------

    filtered = filter_top_sequences(

        dataframe,

        top_n=TOP_N,

        min_distance=MIN_HAMMING_DISTANCE
    )


    sequences = (

        filtered[
            "Sequence"
        ]

        .astype(str)

        .str.upper()

        .tolist()
    )


    top_sequences_by_round[
        round_number
    ] = filtered


    print(

        "Sequences after filtering:",

        len(
            sequences
        )
    )


    # --------------------------------------------------------
    # Calculate HRI matrix
    # --------------------------------------------------------

    (
        hri_array,
        rho,
        n_used

    ) = compute_hri_matrix(
        sequences
    )


    hri_dataframe = pd.DataFrame(

        hri_array,

        index=DINUCLEOTIDE_ORDER,

        columns=DINUCLEOTIDE_ORDER
    )


    HRI_by_round[
        round_number
    ] = hri_dataframe


    rho_by_round[
        round_number
    ] = rho


    n_sequences_by_round[
        round_number
    ] = n_used


# ============================================================
# 7. Convert Figure 2.23a matrices to long format
# ============================================================

figure_2_23a_rows = []


for round_number in range(
    1,
    7
):

    matrix = HRI_by_round[
        round_number
    ]


    for row_dinucleotide in DINUCLEOTIDE_ORDER:

        for column_dinucleotide in DINUCLEOTIDE_ORDER:

            figure_2_23a_rows.append({

                "Round":
                    round_number,

                "Row_dinucleotide":
                    row_dinucleotide,

                "Column_dinucleotide":
                    column_dinucleotide,

                "HRI":
                    matrix.loc[
                        row_dinucleotide,
                        column_dinucleotide
                    ],
            })


figure_2_23a = pd.DataFrame(
    figure_2_23a_rows
)


# ============================================================
# 8. Independent within-class pairs
# ============================================================

def independent_pairs(
    dinucleotides
):

    """
    Return the independent unordered pairs formed from
    a set of dinucleotides, including the diagonal.

    Four dinucleotides therefore give:

        4 diagonal entries
        +
        6 off-diagonal entries
        =
        10 independent entries.
    """

    pairs = []


    for i in range(
        len(
            dinucleotides
        )
    ):

        for j in range(
            i,
            len(
                dinucleotides
            )
        ):

            pairs.append(

                (
                    dinucleotides[i],
                    dinucleotides[j]
                )
            )


    return pairs


WW_WW_PAIRS = independent_pairs(
    WW
)


SS_SS_PAIRS = independent_pairs(
    SS
)


# WW-SS contains all 4 x 4 combinations.

WW_SS_PAIRS = [

    (
        ww,
        ss
    )

    for ww in WW

    for ss in SS
]


assert len(
    WW_WW_PAIRS
) == 10


assert len(
    SS_SS_PAIRS
) == 10


assert len(
    WW_SS_PAIRS
) == 16


# ============================================================
# 9. Sum the three HRI classes
# ============================================================

def sum_hri_pairs(
    matrix,
    pairs
):

    """
    Sum the specified independent entries from a
    symmetric HRI matrix.

    Each unordered pair is counted once.
    """

    return sum(

        matrix.loc[
            dinucleotide_1,
            dinucleotide_2
        ]

        for (
            dinucleotide_1,
            dinucleotide_2
        )

        in pairs
    )


figure_2_23b_rows = []


for round_number in range(
    1,
    7
):

    matrix = HRI_by_round[
        round_number
    ]


    WW_WW_sum = sum_hri_pairs(

        matrix,

        WW_WW_PAIRS
    )


    SS_SS_sum = sum_hri_pairs(

        matrix,

        SS_SS_PAIRS
    )


    WW_SS_sum = sum_hri_pairs(

        matrix,

        WW_SS_PAIRS
    )


    figure_2_23b_rows.append({

        "Round":
            round_number,

        "WW_WW":
            WW_WW_sum,

        "SS_SS":
            SS_SS_sum,

        "WW_SS":
            WW_SS_sum,

        "N_sequences":
            n_sequences_by_round[
                round_number
            ],
    })


figure_2_23b = pd.DataFrame(
    figure_2_23b_rows
)


# ============================================================
# 10. Normalize each trajectory to its Round 6 magnitude
# ============================================================

round_6 = (

    figure_2_23b

    .loc[
        figure_2_23b[
            "Round"
        ] == 6
    ]

    .iloc[0]
)


for category in [

    "WW_WW",

    "SS_SS",

    "WW_SS",
]:

    round_6_magnitude = abs(

        round_6[
            category
        ]
    )


    if (
        round_6_magnitude
        ==
        0
    ):

        figure_2_23b[

            category
            +
            "_normalized"

        ] = np.nan


    else:

        figure_2_23b[

            category
            +
            "_normalized"

        ] = (

            figure_2_23b[
                category
            ]

            /

            round_6_magnitude
        )


# ============================================================
# 11. Sequence-number summary
# ============================================================

figure_2_23_sequence_sets = pd.DataFrame({

    "Round":

        list(
            range(
                1,
                7
            )
        ),

    "N_sequences":

        [
            n_sequences_by_round[
                round_number
            ]

            for round_number in range(
                1,
                7
            )
        ],
})


# ============================================================
# OUTPUT SUMMARY
# ============================================================

# HRI matrices for all six rounds:
#
#     HRI_by_round[1]
#     HRI_by_round[2]
#     ...
#     HRI_by_round[6]
#
#
# Figure 2.23a:
#
#     figure_2_23a
#
# Long-format HRI values for the six heatmaps.
#
#
# Figure 2.23b:
#
#     figure_2_23b
#
# Columns:
#
#     Round
#
#     WW_WW
#         sum of the 10 independent WW-WW HRI values
#
#     SS_SS
#         sum of the 10 independent SS-SS HRI values
#
#     WW_SS
#         sum of the 16 WW-SS HRI values
#
#     WW_WW_normalized
#
#     SS_SS_normalized
#
#     WW_SS_normalized
#
#
# The normalized values are divided by the magnitude
# of the corresponding Round 6 value.
#
# Consequently:
#
#     WW-WW Round 6 -> +1
#
#     SS-SS Round 6 -> +1
#
# and, if WW-SS is negative as expected:
#
#     WW-SS Round 6 -> -1
#
#
# No plotting is performed.