

"""
Code 23 Figure 2-28 nucleosome occurrence GC and poly dAdT.py
==============================================================

WHAT THIS SCRIPT DOES
---------------------
Generates the data underlying Figure 2.28.

Figure 2.28 examines the relationship between the
occurrence of reverse-complement-collapsed 10-mers
within native yeast nucleosomal DNA and two simple
sequence features:

    1. GC content

    2. poly(dA:dT) content

Nucleosomal occurrence was calculated in:

    Code 22 Figure 2-27 10-mer enrichment and yeast
    nucleosome occurrence.py

and is defined as the number of times a given
reverse-complement-collapsed 10-mer occurs within the
147-bp sequences centred on the dyads of the 67,539
mapped yeast nucleosomes.

GC fraction and poly(dA:dT) fraction were calculated in:

    Code 21 Figure 2-26 10-mer GC and poly dAdT analysis.py


FIGURE 2.28
-----------
Panel a:

    nucleosomal occurrence as a function of GC fraction.

Panel b:

    nucleosomal occurrence as a function of
    poly(dA:dT) fraction.


GC CONTENT
----------
GC fraction is:

    number of G or C bases / 10

Possible values are:

    0.0, 0.1, 0.2, ..., 1.0


POLY(dA:dT) CONTENT
-------------------
A poly(dA:dT) tract is defined as an uninterrupted run
of at least 5 consecutive A bases or at least 5
consecutive T bases.

Poly(dA:dT) fraction is:

    number of bases belonging to qualifying A/T tracts
    --------------------------------------------------
                         10


INPUTS
------
figure_2_26

Generated by:

    Code 21 Figure 2-26 10-mer GC and poly dAdT analysis.py

and containing:

    kmer
    GC_count
    GC_fraction
    Poly_dAdT_bases
    Poly_dAdT_fraction


figure_2_27

Generated by:

    Code 22 Figure 2-27 10-mer enrichment and yeast
    nucleosome occurrence.py

and containing:

    kmer
    Nucleosomal_occurrence


OTHER SCRIPTS THAT MUST BE RUN FIRST
------------------------------------
Code 20 Figure 2-25a 10-mer enrichment distribution.py

Code 21 Figure 2-26 10-mer GC and poly dAdT analysis.py

Code 22 Figure 2-27 10-mer enrichment and yeast
nucleosome occurrence.py


OUTPUTS
-------
figure_2_28

    Complete per-10-mer table containing:

        kmer
        GC_count
        GC_fraction
        Poly_dAdT_bases
        Poly_dAdT_fraction
        Nucleosomal_occurrence


figure_2_28_gc

    Data underlying panel a:

        GC_fraction
            vs
        Nucleosomal_occurrence


figure_2_28_poly_dAdT

    Data underlying panel b:

        Poly_dAdT_fraction
            vs
        Nucleosomal_occurrence


figure_2_28_gc_summary

    Summary of nucleosomal occurrence for each
    GC fraction.


figure_2_28_poly_dAdT_summary

    Summary of nucleosomal occurrence for each
    poly(dA:dT) fraction.


No plotting is performed.
"""


import numpy as np
import pandas as pd


# ============================================================
# 1. Check required inputs
# ============================================================

if "figure_2_26" not in globals():

    raise RuntimeError(

        "figure_2_26 is not defined. Run "
        "'Code 21 Figure 2-26 10-mer GC and poly dAdT "
        "analysis.py' first."
    )


if "figure_2_27" not in globals():

    raise RuntimeError(

        "figure_2_27 is not defined. Run "
        "'Code 22 Figure 2-27 10-mer enrichment and "
        "yeast nucleosome occurrence.py' first."
    )


# ============================================================
# 2. Check required columns
# ============================================================

required_2_26_columns = {

    "kmer",

    "GC_count",

    "GC_fraction",

    "Poly_dAdT_bases",

    "Poly_dAdT_fraction",
}


missing_2_26_columns = (

    required_2_26_columns

    -

    set(
        figure_2_26.columns
    )
)


if missing_2_26_columns:

    raise ValueError(

        "figure_2_26 is missing required columns: "
        f"{missing_2_26_columns}"
    )


required_2_27_columns = {

    "kmer",

    "Nucleosomal_occurrence",
}


missing_2_27_columns = (

    required_2_27_columns

    -

    set(
        figure_2_27.columns
    )
)


if missing_2_27_columns:

    raise ValueError(

        "figure_2_27 is missing required columns: "
        f"{missing_2_27_columns}"
    )


# ============================================================
# 3. Construct Figure 2.28 table
# ============================================================

figure_2_28 = (

    figure_2_26[
        [
            "kmer",
            "GC_count",
            "GC_fraction",
            "Poly_dAdT_bases",
            "Poly_dAdT_fraction",
        ]
    ]

    .merge(

        figure_2_27[
            [
                "kmer",
                "Nucleosomal_occurrence",
            ]
        ],

        on="kmer",

        how="inner",

        validate="one_to_one"
    )
)


# ============================================================
# 4. Check that no 10-mers were lost during the merge
# ============================================================

if len(
    figure_2_28
) != len(
    figure_2_26
):

    print(

        "WARNING: number of 10-mers changed during "
        "the merge."
    )


print(
    "Number of 10-mers in Figure 2.28:",
    len(
        figure_2_28
    )
)


# ============================================================
# 5. Figure 2.28a
# ============================================================

figure_2_28_gc = (

    figure_2_28[
        [
            "kmer",
            "GC_count",
            "GC_fraction",
            "Nucleosomal_occurrence",
        ]
    ]

    .copy()
)


# ============================================================
# 6. Figure 2.28b
# ============================================================

figure_2_28_poly_dAdT = (

    figure_2_28[
        [
            "kmer",
            "Poly_dAdT_bases",
            "Poly_dAdT_fraction",
            "Nucleosomal_occurrence",
        ]
    ]

    .copy()
)


# ============================================================
# 7. GC-content summary
# ============================================================

figure_2_28_gc_summary = (

    figure_2_28_gc

    .groupby(
        [
            "GC_count",
            "GC_fraction",
        ],
        as_index=False
    )

    .agg(

        N_10mers=(
            "kmer",
            "size"
        ),

        Mean_nucleosomal_occurrence=(
            "Nucleosomal_occurrence",
            "mean"
        ),

        Median_nucleosomal_occurrence=(
            "Nucleosomal_occurrence",
            "median"
        ),

        SD_nucleosomal_occurrence=(
            "Nucleosomal_occurrence",
            "std"
        )
    )
)


# ============================================================
# 8. poly(dA:dT)-content summary
# ============================================================

figure_2_28_poly_dAdT_summary = (

    figure_2_28_poly_dAdT

    .groupby(
        [
            "Poly_dAdT_bases",
            "Poly_dAdT_fraction",
        ],
        as_index=False
    )

    .agg(

        N_10mers=(
            "kmer",
            "size"
        ),

        Mean_nucleosomal_occurrence=(
            "Nucleosomal_occurrence",
            "mean"
        ),

        Median_nucleosomal_occurrence=(
            "Nucleosomal_occurrence",
            "median"
        ),

        SD_nucleosomal_occurrence=(
            "Nucleosomal_occurrence",
            "std"
        )
    )
)


# ============================================================
# 9. Useful checks
# ============================================================

print(
    "\nGC-content groups:"
)


print(

    figure_2_28_gc_summary

    .to_string(
        index=False
    )
)


print(
    "\npoly(dA:dT)-content groups:"
)


print(

    figure_2_28_poly_dAdT_summary

    .to_string(
        index=False
    )
)


# ============================================================
# OUTPUT SUMMARY
# ============================================================

# Complete Figure 2.28 data:
#
#     figure_2_28
#
#
# Panel a:
#
#     figure_2_28_gc
#
# x:
#
#     GC_fraction
#
# y:
#
#     Nucleosomal_occurrence
#
#
# Panel b:
#
#     figure_2_28_poly_dAdT
#
# x:
#
#     Poly_dAdT_fraction
#
# y:
#
#     Nucleosomal_occurrence
#
#
# Summary tables:
#
#     figure_2_28_gc_summary
#
#     figure_2_28_poly_dAdT_summary
#
#
# All 10-mers are reverse-complement collapsed,
# consistently with Codes 20, 21, and 22.
#
#
# Nucleosomal occurrence is the number of occurrences
# within the 147-bp sequences centred on the dyads of
# the 67,539 mapped yeast nucleosomes.
#
#
# No plotting is performed.