

"""
Code 31 Figures 3-11 and 3-12 10-mer cumulative score sequence properties.py
=============================================================================

WHAT THIS SCRIPT DOES
---------------------
Generates the data underlying Figures 3.11 and 3.12.

100,000 random 147-bp sequences are generated.

Each sequence consists of:

    fixed 17-bp left adapter
    +
    random 113-bp variable region
    +
    fixed 17-bp right adapter


FIGURE 3.11
-----------
For every random sequence, the following are calculated:

    1. 10-mer cumulative score

    2. Mean predicted intrinsic cyclisability

    3. GC fraction

    4. poly(dA:dT) fraction

The 10-mer cumulative score is calculated using the
R6 versus R1 log2 enrichment values generated by:

    Code 20 Figure 2-25a 10-mer enrichment distribution.py

The score is summed over a centred 108-bp region,
corresponding to the optimum identified in Figure 3.10.

The resulting data can be used for the three scatter
plots in Figure 3.11:

    intrinsic cyclisability vs 10-mer cumulative score

    GC fraction vs 10-mer cumulative score

    poly(dA:dT) fraction vs 10-mer cumulative score


FIGURE 3.12
-----------
The same 100,000 random sequences are sorted by increasing
10-mer cumulative score and divided into 10 equally sized
groups of 10,000 sequences.

For every sequence, a Fourier power spectrum is calculated
from the GC-content variation along the central 113 bp.

The mean power spectrum is then calculated separately
for each 10-mer cumulative-score decile.

Helical contrast is also calculated for every sequence as:

    mean power between 8 and 11 bp

    minus

    mean power between 12 and 18 bp

This quantity is compared with 10-mer cumulative score.


VARIABLES THAT MUST ALREADY EXIST
---------------------------------
df_enrichment_rc

    Reverse-complement-collapsed 10-mer enrichment table
    generated by:

        Code 20 Figure 2-25a 10-mer enrichment
        distribution.py

    Required columns:

        kmer
        log2_enrichment


FUNCTIONS THAT MUST ALREADY EXIST
---------------------------------
canonical_kmer

    Defined by:

        Code 20 Figure 2-25a 10-mer enrichment
        distribution.py


load_model

pred

    External intrinsic-cyclisability prediction
    functions used throughout the thesis.


OTHER SCRIPTS THAT MUST BE RUN FIRST
------------------------------------
Code 20 Figure 2-25a 10-mer enrichment distribution.py

This provides:

    df_enrichment_rc
    canonical_kmer


OUTPUTS
-------
random_sequences

    The 100,000 generated 147-bp sequences.


tenmer_cumulative_score

    108-bp 10-mer cumulative score for every sequence.


c0_mean

    Mean predicted intrinsic cyclisability.


GC_fraction

    GC fraction of the central 113 bp.


Poly_dAdT_fraction

    Fraction of the central 113 bp belonging to
    poly(dA:dT) tracts.


figure_3_11

    Complete sequence-level data for Figure 3.11.


figure_3_11_correlations

    Pearson correlations for all three Figure 3.11
    relationships.


figure_3_12_spectra

    Mean GC Fourier power spectrum for each of the
    10 cumulative-score deciles.


figure_3_12_helical_contrast

    Sequence-level 10-mer cumulative score and
    GC helical contrast.


figure_3_12_correlation

    Pearson correlation between helical contrast
    and 10-mer cumulative score.


NOTES
-----
No plotting is performed.
"""


import numpy as np
import pandas as pd

from scipy.stats import pearsonr


# ============================================================
# 1. Parameters
# ============================================================

N_RANDOM = 100000

SEQUENCE_LENGTH = 147

VARIABLE_LENGTH = 113

K = 10

SCORE_WINDOW = 108


LEFT_ADAPTER = (
    "CTTATCTCCCACCGTCC"
)

RIGHT_ADAPTER = (
    "GGCAGAAGACAAGGGAA"
)


assert len(
    LEFT_ADAPTER
) == 17

assert len(
    RIGHT_ADAPTER
) == 17


# Fourier-analysis parameters.

FOURIER_LENGTH = 113

FOURIER_WINDOW = np.hanning(
    FOURIER_LENGTH
)

FOURIER_U = np.mean(
    FOURIER_WINDOW ** 2
)


# ============================================================
# 2. Check required inputs
# ============================================================

if "df_enrichment_rc" not in globals():

    raise RuntimeError(
        "df_enrichment_rc must already exist. "
        "Run Code 20 Figure 2-25a 10-mer enrichment "
        "distribution.py first."
    )


if "canonical_kmer" not in globals():

    raise RuntimeError(
        "canonical_kmer must already exist. "
        "Run Code 20 Figure 2-25a 10-mer enrichment "
        "distribution.py first."
    )


if "load_model" not in globals():

    raise RuntimeError(
        "load_model must already be defined."
    )


if "pred" not in globals():

    raise RuntimeError(
        "pred must already be defined."
    )


required_columns = [
    "kmer",
    "log2_enrichment"
]


for column in required_columns:

    if column not in df_enrichment_rc.columns:

        raise ValueError(
            f"df_enrichment_rc must contain "
            f"the column '{column}'."
        )


# ============================================================
# 3. Construct 10-mer score dictionary
# ============================================================

tenmer_score_dict = dict(

    zip(

        df_enrichment_rc[
            "kmer"
        ],

        df_enrichment_rc[
            "log2_enrichment"
        ]
    )
)


def get_10mer_score(
    kmer
):

    """
    Return the R6 versus R1 log2 enrichment value of
    a 10-mer after reverse-complement collapse.
    """

    canonical = canonical_kmer(
        kmer
    )


    if canonical not in tenmer_score_dict:

        raise KeyError(
            f"10-mer '{kmer}' "
            f"(canonical '{canonical}') "
            "was not found in df_enrichment_rc."
        )


    return tenmer_score_dict[
        canonical
    ]


# ============================================================
# 4. Generate 100,000 random sequences
# ============================================================

# A fixed seed is used so that the generated random dataset
# can be reproduced exactly.

rng = np.random.default_rng(
    0
)


bases = np.array(
    ["A", "C", "G", "T"]
)


random_central_array = rng.choice(

    bases,

    size=(
        N_RANDOM,
        VARIABLE_LENGTH
    )
)


random_central = [

    "".join(row)

    for row in random_central_array
]


random_sequences = [

    LEFT_ADAPTER
    +
    central
    +
    RIGHT_ADAPTER

    for central in random_central
]


assert len(
    random_sequences
) == N_RANDOM


assert all(
    len(sequence) == SEQUENCE_LENGTH
    for sequence in random_sequences
)


# ============================================================
# 5. Calculate 108-bp 10-mer cumulative score
# ============================================================

def compute_10mer_cumulative_score(
    sequence,
    window_size=108
):

    """
    Calculate the 10-mer cumulative score over a centred
    region of the 147-bp sequence.
    """

    start = (
        SEQUENCE_LENGTH
        -
        window_size
    ) // 2


    central = sequence[
        start:
        start + window_size
    ]


    score = 0.0


    for i in range(
        window_size - K + 1
    ):

        kmer = central[
            i:
            i + K
        ]


        score += get_10mer_score(
            kmer
        )


    return score


tenmer_cumulative_score = np.asarray([

    compute_10mer_cumulative_score(
        sequence,
        SCORE_WINDOW
    )

    for sequence in random_sequences

])


assert len(
    tenmer_cumulative_score
) == N_RANDOM


# ============================================================
# 6. Predict intrinsic-cyclisability profiles
# ============================================================

# Every 147-bp sequence contains 98 overlapping
# 50-bp windows.

C0_WINDOW = 50

C0_PROFILE_LENGTH = (
    SEQUENCE_LENGTH
    -
    C0_WINDOW
    +
    1
)  # 98


model_c0 = load_model(
    0
)


# Prediction is performed in batches so that all
# 9.8 million 50-bp windows do not need to be stored
# simultaneously.

SEQUENCE_BATCH_SIZE = 1000


c0_mean = np.empty(
    N_RANDOM,
    dtype=float
)


for batch_start in range(
    0,
    N_RANDOM,
    SEQUENCE_BATCH_SIZE
):

    batch_end = min(

        batch_start
        +
        SEQUENCE_BATCH_SIZE,

        N_RANDOM
    )


    batch_sequences = random_sequences[
        batch_start:
        batch_end
    ]


    windows = [

        sequence[
            i:
            i + C0_WINDOW
        ]

        for sequence in batch_sequences

        for i in range(
            C0_PROFILE_LENGTH
        )
    ]


    predictions = np.asarray(

        pred(
            model_c0,
            windows
        )

    ).reshape(
        len(batch_sequences),
        C0_PROFILE_LENGTH
    )


    c0_mean[
        batch_start:
        batch_end
    ] = np.mean(
        predictions,
        axis=1
    )


assert len(
    c0_mean
) == N_RANDOM


# ============================================================
# 7. Calculate GC fraction
# ============================================================

GC_fraction = np.asarray([

    (
        central.count("G")
        +
        central.count("C")
    )

    /
    VARIABLE_LENGTH

    for central in random_central

])


# ============================================================
# 8. Calculate poly(dA:dT) fraction
# ============================================================

def poly_dAdT_fraction(
    sequence,
    minimum_run=5
):

    """
    Calculate the fraction of bases belonging to
    uninterrupted homopolymeric A or T runs of at least
    minimum_run bases.
    """

    qualifying_bases = 0

    i = 0


    while i < len(sequence):

        base = sequence[i]


        if base not in {
            "A",
            "T"
        }:

            i += 1

            continue


        j = i + 1


        while (
            j < len(sequence)
            and sequence[j] == base
        ):

            j += 1


        run_length = (
            j - i
        )


        if run_length >= minimum_run:

            qualifying_bases += (
                run_length
            )


        i = j


    return (
        qualifying_bases
        /
        len(sequence)
    )


Poly_dAdT_fraction = np.asarray([

    poly_dAdT_fraction(
        central
    )

    for central in random_central

])


# ============================================================
# 9. Figure 3.11 sequence-level data
# ============================================================

figure_3_11 = pd.DataFrame({

    "Sequence":
        random_sequences,

    "Central_113":
        random_central,

    "Tenmer_cumulative_score":
        tenmer_cumulative_score,

    "Mean_intrinsic_cyclisability":
        c0_mean,

    "GC_fraction":
        GC_fraction,

    "Poly_dAdT_fraction":
        Poly_dAdT_fraction
})


# ============================================================
# 10. Figure 3.11 correlations
# ============================================================

def calculate_correlation(
    x,
    y
):

    """
    Pearson correlation using finite values only.
    """

    x = np.asarray(
        x,
        dtype=float
    )

    y = np.asarray(
        y,
        dtype=float
    )


    valid = (

        np.isfinite(x)

        &

        np.isfinite(y)
    )


    r, p = pearsonr(

        x[
            valid
        ],

        y[
            valid
        ]
    )


    return (
        int(valid.sum()),
        r,
        p
    )


n_c0, r_c0, p_c0 = calculate_correlation(

    tenmer_cumulative_score,

    c0_mean
)


n_gc, r_gc, p_gc = calculate_correlation(

    tenmer_cumulative_score,

    GC_fraction
)


n_poly, r_poly, p_poly = calculate_correlation(

    tenmer_cumulative_score,

    Poly_dAdT_fraction
)


figure_3_11_correlations = pd.DataFrame({

    "Property": [

        "Mean intrinsic cyclisability",

        "GC fraction",

        "Poly(dA:dT) fraction"
    ],

    "N": [

        n_c0,

        n_gc,

        n_poly
    ],

    "Pearson_r": [

        r_c0,

        r_gc,

        r_poly
    ],

    "P_value": [

        p_c0,

        p_gc,

        p_poly
    ]
})


# ============================================================
# 11. GC indicator matrix for Fourier analysis
# ============================================================

# Each central 113-bp sequence is represented as:
#
#     1 = G or C
#     0 = A or T


gc_matrix = np.asarray([

    [
        1.0
        if base in {"G", "C"}
        else 0.0

        for base in central
    ]

    for central in random_central

])


assert gc_matrix.shape == (
    N_RANDOM,
    113
)


# ============================================================
# 12. Mean-subtract each individual sequence
# ============================================================

gc_centered = (

    gc_matrix

    -

    np.mean(
        gc_matrix,
        axis=1,
        keepdims=True
    )
)


# ============================================================
# 13. Apply Hann window
# ============================================================

gc_windowed = (

    gc_centered

    *

    FOURIER_WINDOW[
        None,
        :
    ]
)


# ============================================================
# 14. Fourier transform
# ============================================================

gc_fft = np.fft.rfft(

    gc_windowed,

    axis=1
)


gc_power = (

    np.abs(
        gc_fft
    ) ** 2

    /

    (
        FOURIER_LENGTH ** 2

        *

        FOURIER_U
    )
)


# ============================================================
# 15. Remove the zero-frequency component
# ============================================================

k_values = np.arange(

    1,

    gc_power.shape[1]
)


periodicity = (

    FOURIER_LENGTH

    /

    k_values
)


gc_power_nonzero = gc_power[
    :,
    1:
]


assert gc_power_nonzero.shape[1] == len(
    periodicity
)


# ============================================================
# 16. Divide sequences into cumulative-score deciles
# ============================================================

# Sort from lowest to highest 10-mer cumulative score.

score_order = np.argsort(
    tenmer_cumulative_score
)


# With exactly 100,000 sequences, every decile contains
# exactly 10,000 sequences.

score_deciles = np.empty(
    N_RANDOM,
    dtype=int
)


for decile in range(
    10
):

    start = (
        decile
        *
        10000
    )

    end = (
        start
        +
        10000
    )


    indices = score_order[
        start:
        end
    ]


    score_deciles[
        indices
    ] = (
        decile + 1
    )


assert np.all(

    np.bincount(
        score_deciles
    )[1:]

    == 10000
)


# Add decile to Figure 3.11 table as it is useful for
# Figure 3.12.

figure_3_11[
    "Tenmer_score_decile"
] = score_deciles


# ============================================================
# 17. Mean power spectrum of each score decile
# ============================================================

spectra_rows = []


for decile in range(
    1,
    11
):

    mask = (
        score_deciles
        ==
        decile
    )


    mean_power = np.mean(

        gc_power_nonzero[
            mask,
            :
        ],

        axis=0
    )


    mean_score = np.mean(

        tenmer_cumulative_score[
            mask
        ]
    )


    min_score = np.min(

        tenmer_cumulative_score[
            mask
        ]
    )


    max_score = np.max(

        tenmer_cumulative_score[
            mask
        ]
    )


    for period, power in zip(

        periodicity,

        mean_power
    ):

        spectra_rows.append({

            "Decile":
                decile,

            "N_sequences":
                int(
                    mask.sum()
                ),

            "Mean_10mer_cumulative_score":
                mean_score,

            "Minimum_10mer_cumulative_score":
                min_score,

            "Maximum_10mer_cumulative_score":
                max_score,

            "Periodicity_bp":
                period,

            "Mean_power":
                power
        })


figure_3_12_spectra = pd.DataFrame(
    spectra_rows
)


# ============================================================
# 18. Calculate helical contrast
# ============================================================

# Thesis definition:
#
# mean power from 8-11 bp
#
# minus
#
# mean power from 12-18 bp.


helical_mask = (

    (periodicity >= 8)

    &

    (periodicity <= 11)
)


background_mask = (

    (periodicity >= 12)

    &

    (periodicity <= 18)
)


mean_helical_power = np.mean(

    gc_power_nonzero[
        :,
        helical_mask
    ],

    axis=1
)


mean_background_power = np.mean(

    gc_power_nonzero[
        :,
        background_mask
    ],

    axis=1
)


helical_contrast = (

    mean_helical_power

    -

    mean_background_power
)


# ============================================================
# 19. Figure 3.12 helical-contrast data
# ============================================================

figure_3_12_helical_contrast = pd.DataFrame({

    "Sequence":
        random_sequences,

    "Tenmer_cumulative_score":
        tenmer_cumulative_score,

    "Tenmer_score_decile":
        score_deciles,

    "Mean_power_8_to_11_bp":
        mean_helical_power,

    "Mean_power_12_to_18_bp":
        mean_background_power,

    "Helical_contrast":
        helical_contrast
})


# ============================================================
# 20. Correlation between helical contrast and 10-mer score
# ============================================================

n_contrast, r_contrast, p_contrast = (
    calculate_correlation(

        tenmer_cumulative_score,

        helical_contrast
    )
)


figure_3_12_correlation = pd.DataFrame({

    "N": [
        n_contrast
    ],

    "Pearson_r": [
        r_contrast
    ],

    "P_value": [
        p_contrast
    ]
})


# ============================================================
# 21. Decile summary
# ============================================================

figure_3_12_decile_summary = (

    figure_3_12_helical_contrast

    .groupby(
        "Tenmer_score_decile",
        as_index=False
    )

    .agg(

        N_sequences=(
            "Sequence",
            "size"
        ),

        Mean_10mer_cumulative_score=(
            "Tenmer_cumulative_score",
            "mean"
        ),

        Mean_helical_contrast=(
            "Helical_contrast",
            "mean"
        ),

        SD_helical_contrast=(
            "Helical_contrast",
            "std"
        )
    )
)


# ============================================================
# 22. Final checks
# ============================================================

assert len(
    figure_3_11
) == 100000


assert len(
    figure_3_12_helical_contrast
) == 100000


assert len(
    figure_3_12_decile_summary
) == 10


assert np.all(

    figure_3_12_decile_summary[
        "N_sequences"
    ].to_numpy()

    == 10000
)


# ============================================================
# 23. Report Figure 3.11 results
# ============================================================

print(
    "\nFigure 3.11"
)


print(
    "10-mer cumulative score versus sequence properties"
)


print(
    "\nMean intrinsic cyclisability:"
)

print(
    f"Pearson r = {r_c0:.4f}"
)

print(
    f"P = {p_c0:.4g}"
)


print(
    "\nGC fraction:"
)

print(
    f"Pearson r = {r_gc:.4f}"
)

print(
    f"P = {p_gc:.4g}"
)


print(
    "\nPoly(dA:dT) fraction:"
)

print(
    f"Pearson r = {r_poly:.4f}"
)

print(
    f"P = {p_poly:.4g}"
)


# ============================================================
# 24. Report Figure 3.12 result
# ============================================================

print(
    "\nFigure 3.12"
)


print(
    "GC helical contrast versus "
    "10-mer cumulative score"
)


print(
    f"Pearson r = {r_contrast:.4f}"
)

print(
    f"P = {p_contrast:.4g}"
)


# ============================================================
# OUTPUT SUMMARY
# ============================================================

# Generated sequences:
#
#     random_sequences
#
#
# Central 113-bp variable regions:
#
#     random_central
#
#
# 108-bp 10-mer cumulative scores:
#
#     tenmer_cumulative_score
#
#
# ============================================================
# FIGURE 3.11
# ============================================================
#
# Complete sequence-level data:
#
#     figure_3_11
#
#
# Correlation statistics:
#
#     figure_3_11_correlations
#
#
# ============================================================
# FIGURE 3.12 LEFT PANEL
# ============================================================
#
# Mean GC power spectrum for each of the ten
# 10-mer cumulative-score deciles:
#
#     figure_3_12_spectra
#
#
# Decile summary:
#
#     figure_3_12_decile_summary
#
#
# ============================================================
# FIGURE 3.12 RIGHT PANEL
# ============================================================
#
# Sequence-level helical contrast:
#
#     figure_3_12_helical_contrast
#
#
# Correlation statistics:
#
#     figure_3_12_correlation
#
#
# No plotting is performed.