

"""
Code 17 Figure 2-22 HRI heatmaps.py
====================================

WHAT THIS SCRIPT DOES
---------------------
Generates the data underlying Figure 2.22.

Figure 2.22 compares Helical Repetition Index (HRI)
matrices for four sequence groups:

    1. 9,803 randomly selected unique Round 1 sequences

    2. 9,803 most enriched Round 6 sequences

    3. 9,803 weakest-positioned native yeast nucleosomes

    4. 9,803 strongest-positioned native yeast nucleosomes


For every sequence, only the central 113-bp region is used.

A 113-bp sequence contains 112 possible dinucleotide
start positions.


PAIRWISE DISTRIBUTION
---------------------
For each unordered dinucleotide pair and separation d,
occurrences are pooled across the complete sequence set.

For identical dinucleotide pairs, the random expectation is:

    (112 - d) / 256

per sequence.

For non-identical unordered pairs, both orientations are
counted, giving:

    (112 - d) / 128

per sequence.

The normalized pairwise distribution is:

              observed pooled count
    rho(d) = -------------------------
              expected pooled count


HELICAL REPETITION INDEX
------------------------
The full-helical target separations are:

    10, 20, 30, ..., 110 bp

The half-helical target separations are:

    5, 15, 25, ..., 105 bp

For each target separation c, the maximum rho value within
the three-point interval:

    c - 1, c, c + 1

is used.

The HRI is then:

    HRI = sum(full-helical maxima)
          -
          sum(half-helical maxima)

Thus:

    positive HRI
        preference for full-helical-repeat spacing

    negative HRI
        preference for half-helical-repeat spacing


DINUCLEOTIDE PAIRS
------------------
All 136 unordered pairs of the 16 dinucleotides are
calculated.

The resulting matrix is symmetric because pair order is
not distinguished.


DINUCLEOTIDE ORDER
------------------
The heatmaps use:

    AA, AT, TA, TT,
    AC, AG, CA, CT, GA, GT, TC, TG,
    CC, CG, GC, GG

This places WW dinucleotides first, mixed dinucleotides
in the middle, and SS dinucleotides last.


INPUT FILES
-----------
R1.csv
R6.csv

Each CSV must contain:

    Sequence
    Counts Per Million


VARIABLES THAT MUST ALREADY EXIST
---------------------------------
native_nucleosomes

Generated by:

    Code 5 Native yeast nucleosomal sequences.py

Expected columns:

    Sequence
    NCP_score


OTHER SCRIPTS THAT MUST BE RUN FIRST
------------------------------------
Code 5 Native yeast nucleosomal sequences.py


ROUND 6 SEQUENCES
-----------------
The top 10,000 Round 6 sequences are initially selected
by Counts Per Million.

Near-duplicate sequences differing at fewer than 10
positions are removed, retaining the higher-abundance
sequence.

This gives 9,803 sequences.


ROUND 1 SEQUENCES
-----------------
9,803 unique valid Round 1 sequences are selected randomly.

The random seed is:

    42


NATIVE YEAST SEQUENCES
----------------------
Native nucleosomes are ranked by NCP score.

The 9,803 sequences with the lowest NCP scores are used
as the weakest-positioned nucleosomes.

The 9,803 sequences with the highest NCP scores are used
as the strongest-positioned nucleosomes.


OUTPUTS
-------
HRI_R1_random
HRI_R6_top
HRI_yeast_weak
HRI_yeast_strong

    16 x 16 DataFrames containing the HRI matrices.

figure_2_22

    Long-format DataFrame containing all four matrices.

No plotting is performed.
"""


import random

import numpy as np
import pandas as pd


# ============================================================
# 1. Analysis settings
# ============================================================

R1_FILE = "R1.csv"

R6_FILE = "R6.csv"


N_SEQUENCES = 9803

TOP_N = 10_000

MIN_HAMMING_DISTANCE = 10


RANDOM_SEED = 42


RAW_LENGTH = 147

TRIM = 17

SEQ_LEN = 113

DINUC_STARTS = (
    SEQ_LEN - 1
)


# ============================================================
# 2. HRI separation distances
# ============================================================

# Full helical repeats.

HELIX = np.arange(
    10,
    111,
    10
)


# Odd multiples of approximately half a helical repeat.

HALF = np.arange(
    5,
    106,
    10
)


# For each nominal separation, examine +/- 1 bp.

DISTS = np.array(

    sorted(

        set(

            [
                x

                for centre in HELIX

                for x in (
                    centre - 1,
                    centre,
                    centre + 1
                )
            ]

            +

            [
                x

                for centre in HALF

                for x in (
                    centre - 1,
                    centre,
                    centre + 1
                )
            ]
        )
    ),

    dtype=int
)


# ============================================================
# 3. Dinucleotides and matrix ordering
# ============================================================

DINUCS = [

    a + b

    for a in "ACGT"

    for b in "ACGT"
]


# All 136 unordered dinucleotide pairs.

PAIRS = [

    (i, j)

    for i in range(16)

    for j in range(
        i,
        16
    )
]


# Ordering used for Figure 2.22.

DINUCLEOTIDE_ORDER = [

    "AA",
    "AT",
    "TA",
    "TT",

    "AC",
    "AG",
    "CA",
    "CT",
    "GA",
    "GT",
    "TC",
    "TG",

    "CC",
    "CG",
    "GC",
    "GG",
]


ORDER_INDEX = [

    DINUCS.index(
        dinucleotide
    )

    for dinucleotide
    in DINUCLEOTIDE_ORDER
]


BASE_MAP = {

    ord("A"): 0,

    ord("C"): 1,

    ord("G"): 2,

    ord("T"): 3,
}


VALID_BASES = set(
    "ACGT"
)


# ============================================================
# 4. Load SELEX data
# ============================================================

def load_selex_csv(
    filename
):

    """
    Load a SELEX CSV and check the required columns.
    """

    df = pd.read_csv(
        filename
    )


    required_columns = {
        "Sequence",
        "Counts Per Million",
    }


    missing_columns = (

        required_columns

        -

        set(
            df.columns
        )
    )


    if missing_columns:

        raise ValueError(
            f"{filename} is missing columns: "
            f"{missing_columns}"
        )


    df["Sequence"] = (

        df["Sequence"]

        .astype(str)

        .str.upper()
    )


    return df


df_R1 = load_selex_csv(
    R1_FILE
)


df_R6 = load_selex_csv(
    R6_FILE
)


# ============================================================
# 5. Hamming distance
# ============================================================

def hamming_distance(
    sequence_1,
    sequence_2
):

    """
    Number of positions at which two equal-length
    sequences differ.
    """

    return sum(

        base_1 != base_2

        for base_1, base_2
        in zip(
            sequence_1,
            sequence_2
        )
    )


# ============================================================
# 6. Select and filter top Round 6 sequences
# ============================================================

def filter_top_sequences(
    dataframe,
    top_n=TOP_N,
    min_distance=MIN_HAMMING_DISTANCE
):

    """
    Rank sequences by Counts Per Million.

    Initially select the top N sequences.

    Process sequences from highest to lowest abundance,
    retaining a sequence only if it differs from every
    previously retained sequence at at least
    `min_distance` positions.
    """

    top = (

        dataframe

        .sort_values(
            "Counts Per Million",
            ascending=False
        )

        .head(
            top_n
        )

        .reset_index(
            drop=True
        )
    )


    retained_rows = []

    retained_sequences = []


    for _, row in top.iterrows():

        sequence = row[
            "Sequence"
        ]


        keep = True


        for previous_sequence in retained_sequences:

            if hamming_distance(
                sequence,
                previous_sequence
            ) < min_distance:

                keep = False

                break


        if keep:

            retained_rows.append(
                row
            )

            retained_sequences.append(
                sequence
            )


    return (

        pd.DataFrame(
            retained_rows
        )

        .reset_index(
            drop=True
        )
    )


df_R6_top = filter_top_sequences(
    df_R6
)


print(
    "Filtered top R6 sequences:",
    len(
        df_R6_top
    )
)


if len(
    df_R6_top
) != N_SEQUENCES:

    print(
        "\nWARNING:"
        "\nExpected 9,803 filtered Round 6 sequences, "
        f"but found {len(df_R6_top)}."
    )


# ============================================================
# 7. Random Round 1 sequences
# ============================================================

# Keep only valid 147-bp sequences.

R1_valid_sequences = [

    sequence

    for sequence in (
        df_R1[
            "Sequence"
        ]
        .astype(str)
        .str.upper()
        .tolist()
    )

    if (
        len(sequence) == RAW_LENGTH

        and

        set(sequence) <= VALID_BASES
    )
]


# Ensure uniqueness.

R1_valid_sequences = list(
    set(
        R1_valid_sequences
    )
)


print(
    "Valid unique R1 sequences:",
    len(
        R1_valid_sequences
    )
)


if len(
    R1_valid_sequences
) < N_SEQUENCES:

    raise ValueError(
        "There are fewer than 9,803 valid unique "
        "Round 1 sequences."
    )


# Match the sequence number used for the R6 analysis.

random.seed(
    RANDOM_SEED
)


R1_random_sequences = random.sample(
    R1_valid_sequences,
    N_SEQUENCES
)


# ============================================================
# 8. Round 6 sequence list
# ============================================================

R6_top_sequences = (

    df_R6_top[
        "Sequence"
    ]

    .astype(str)

    .str.upper()

    .tolist()
)


# ============================================================
# 9. Native yeast sequence sets
# ============================================================

if "native_nucleosomes" not in globals():

    raise RuntimeError(
        "native_nucleosomes is not defined. "
        "Run 'Code 5 Native yeast nucleosomal sequences.py' "
        "before this script."
    )


required_native_columns = {
    "Sequence",
    "NCP_score",
}


missing_native_columns = (

    required_native_columns

    -

    set(
        native_nucleosomes.columns
    )
)


if missing_native_columns:

    raise ValueError(
        "native_nucleosomes is missing columns: "
        f"{missing_native_columns}"
    )


native_valid = (

    native_nucleosomes

    .copy()
)


native_valid[
    "Sequence"
] = (

    native_valid[
        "Sequence"
    ]

    .astype(str)

    .str.upper()
)


native_valid = (

    native_valid.loc[

        native_valid[
            "Sequence"
        ]

        .apply(

            lambda sequence:

            (
                len(sequence)
                ==
                RAW_LENGTH

                and

                set(sequence)
                <=
                VALID_BASES
            )
        )
    ]

    .copy()
)


if len(
    native_valid
) < N_SEQUENCES:

    raise ValueError(
        "There are fewer than 9,803 valid native "
        "yeast nucleosome sequences."
    )


# Weakest-positioned nucleosomes.

yeast_weak_sequences = (

    native_valid

    .nsmallest(
        N_SEQUENCES,
        "NCP_score"
    )[
        "Sequence"
    ]

    .tolist()
)


# Strongest-positioned nucleosomes.

yeast_strong_sequences = (

    native_valid

    .nlargest(
        N_SEQUENCES,
        "NCP_score"
    )[
        "Sequence"
    ]

    .tolist()
)


# ============================================================
# 10. Extract central 113 bp
# ============================================================

def central_113_sequences(
    sequences
):

    """
    Extract the central 113-bp variable region from
    valid 147-bp sequences.
    """

    output = []


    for sequence in sequences:

        sequence = str(
            sequence
        ).upper()


        if len(
            sequence
        ) != RAW_LENGTH:

            continue


        core = sequence[
            TRIM:
            RAW_LENGTH - TRIM
        ]


        if (
            len(core) == SEQ_LEN

            and

            set(core) <= VALID_BASES
        ):

            output.append(
                core
            )


    return output


# ============================================================
# 11. Exact normalization constants
# ============================================================

# M[pair, distance] is the expected number of occurrences
# in one random 113-bp sequence at that separation.
#
# Identical pair:
#
#     (112 - d) / 256
#
# Different unordered pair:
#
#     (112 - d) / 128

M = np.zeros(
    (
        len(PAIRS),
        len(DISTS)
    ),
    dtype=float
)


for pair_index, (
    dinucleotide_1,
    dinucleotide_2
) in enumerate(
    PAIRS
):

    if (
        dinucleotide_1
        ==
        dinucleotide_2
    ):

        denominator = 256.0


    else:

        denominator = 128.0


    M[
        pair_index,
        :
    ] = (

        DINUC_STARTS

        -

        DISTS

    ) / denominator


# ============================================================
# 12. Convert one sequence to dinucleotide bit masks
# ============================================================

def sequence_to_masks(
    sequence
):

    """
    Encode the start positions of each of the 16
    dinucleotides as integer bit masks.

    Bit p is 1 when the corresponding dinucleotide
    starts at position p.
    """

    sequence_bytes = (
        sequence.encode(
            "ascii"
        )
    )


    masks = [
        0
    ] * 16


    for position in range(
        DINUC_STARTS
    ):

        code = (

            BASE_MAP[
                sequence_bytes[
                    position
                ]
            ]

            << 2

        ) | BASE_MAP[
            sequence_bytes[
                position + 1
            ]
        ]


        masks[
            code
        ] |= (
            1
            <<
            position
        )


    return masks


# ============================================================
# 13. Calculate one HRI matrix
# ============================================================

def compute_hri_matrix(
    full_sequences
):

    """
    Calculate the 16 x 16 symmetric HRI matrix for
    one sequence set.

    Pair counts are pooled across the entire sequence
    group before normalization.
    """

    sequences = central_113_sequences(
        full_sequences
    )


    total_counts = np.zeros(
        (
            len(PAIRS),
            len(DISTS)
        ),
        dtype=float
    )


    n_used = 0


    # --------------------------------------------------------
    # Accumulate pair counts
    # --------------------------------------------------------

    for sequence in sequences:

        masks = sequence_to_masks(
            sequence
        )


        for distance_index, distance in enumerate(
            DISTS
        ):

            shifted_masks = [

                mask
                >>
                int(distance)

                for mask in masks
            ]


            for pair_index, (
                dinucleotide_1,
                dinucleotide_2
            ) in enumerate(
                PAIRS
            ):


                # Identical pair.

                if (
                    dinucleotide_1
                    ==
                    dinucleotide_2
                ):

                    count = (

                        masks[
                            dinucleotide_1
                        ]

                        &

                        shifted_masks[
                            dinucleotide_1
                        ]

                    ).bit_count()


                # Different unordered pair:
                # count both orientations.

                else:

                    count = (

                        (
                            masks[
                                dinucleotide_1
                            ]

                            &

                            shifted_masks[
                                dinucleotide_2
                            ]

                        ).bit_count()

                        +

                        (
                            masks[
                                dinucleotide_2
                            ]

                            &

                            shifted_masks[
                                dinucleotide_1
                            ]

                        ).bit_count()
                    )


                total_counts[
                    pair_index,
                    distance_index
                ] += count


        n_used += 1


    print(
        "Sequences used:",
        n_used
    )


    if n_used == 0:

        raise ValueError(
            "No valid sequences were available for "
            "HRI calculation."
        )


    # --------------------------------------------------------
    # Normalized pairwise distribution rho(d)
    # --------------------------------------------------------

    rho = (

        total_counts

        /

        (
            n_used
            *
            M
        )
    )


    # --------------------------------------------------------
    # Calculate HRI
    # --------------------------------------------------------

    hri = np.zeros(
        len(PAIRS),
        dtype=float
    )


    # Add maxima around full-helical separations.

    for centre in HELIX:

        centre_index = np.where(
            DISTS == centre
        )[0][0]


        hri += np.max(

            rho[
                :,
                centre_index - 1:
                centre_index + 2
            ],

            axis=1
        )


    # Subtract maxima around half-helical separations.

    for centre in HALF:

        centre_index = np.where(
            DISTS == centre
        )[0][0]


        hri -= np.max(

            rho[
                :,
                centre_index - 1:
                centre_index + 2
            ],

            axis=1
        )


    # --------------------------------------------------------
    # Convert 136 HRI values into symmetric 16 x 16 matrix
    # --------------------------------------------------------

    hri_matrix = np.zeros(
        (
            16,
            16
        ),
        dtype=float
    )


    for value, (
        dinucleotide_1,
        dinucleotide_2
    ) in zip(
        hri,
        PAIRS
    ):

        hri_matrix[
            dinucleotide_1,
            dinucleotide_2
        ] = value


        hri_matrix[
            dinucleotide_2,
            dinucleotide_1
        ] = value


    # --------------------------------------------------------
    # Reorder for Figure 2.22
    # --------------------------------------------------------

    hri_matrix_ordered = (

        hri_matrix[
            np.ix_(
                ORDER_INDEX,
                ORDER_INDEX
            )
        ]
    )


    return (
        hri_matrix_ordered,
        rho,
        n_used
    )


# ============================================================
# 14. Calculate all four Figure 2.22 matrices
# ============================================================

print(
    "\nR1 random"
)

(
    HRI_R1_random_array,
    rho_R1_random,
    n_R1_random

) = compute_hri_matrix(
    R1_random_sequences
)


print(
    "\nR6 top"
)

(
    HRI_R6_top_array,
    rho_R6_top,
    n_R6_top

) = compute_hri_matrix(
    R6_top_sequences
)


print(
    "\nYeast weak"
)

(
    HRI_yeast_weak_array,
    rho_yeast_weak,
    n_yeast_weak

) = compute_hri_matrix(
    yeast_weak_sequences
)


print(
    "\nYeast strong"
)

(
    HRI_yeast_strong_array,
    rho_yeast_strong,
    n_yeast_strong

) = compute_hri_matrix(
    yeast_strong_sequences
)


# ============================================================
# 15. Labelled HRI matrices
# ============================================================

HRI_R1_random = pd.DataFrame(

    HRI_R1_random_array,

    index=DINUCLEOTIDE_ORDER,

    columns=DINUCLEOTIDE_ORDER
)


HRI_R6_top = pd.DataFrame(

    HRI_R6_top_array,

    index=DINUCLEOTIDE_ORDER,

    columns=DINUCLEOTIDE_ORDER
)


HRI_yeast_weak = pd.DataFrame(

    HRI_yeast_weak_array,

    index=DINUCLEOTIDE_ORDER,

    columns=DINUCLEOTIDE_ORDER
)


HRI_yeast_strong = pd.DataFrame(

    HRI_yeast_strong_array,

    index=DINUCLEOTIDE_ORDER,

    columns=DINUCLEOTIDE_ORDER
)


# ============================================================
# 16. Long-format Figure 2.22 output
# ============================================================

def matrix_to_long(
    matrix,
    dataset
):

    """
    Convert a labelled HRI matrix to long format.
    """

    rows = []


    for row_dinucleotide in DINUCLEOTIDE_ORDER:

        for column_dinucleotide in DINUCLEOTIDE_ORDER:

            rows.append({

                "Dataset":
                    dataset,

                "Row_dinucleotide":
                    row_dinucleotide,

                "Column_dinucleotide":
                    column_dinucleotide,

                "HRI":
                    matrix.loc[
                        row_dinucleotide,
                        column_dinucleotide
                    ],
            })


    return pd.DataFrame(
        rows
    )


figure_2_22 = pd.concat(

    [

        matrix_to_long(
            HRI_R1_random,
            "R1_random"
        ),

        matrix_to_long(
            HRI_R6_top,
            "R6_top"
        ),

        matrix_to_long(
            HRI_yeast_weak,
            "Yeast_weak"
        ),

        matrix_to_long(
            HRI_yeast_strong,
            "Yeast_strong"
        ),
    ],

    ignore_index=True
)


# ============================================================
# 17. Sequence-set summary
# ============================================================

figure_2_22_sequence_sets = pd.DataFrame({

    "Dataset": [

        "R1_random",
        "R6_top",
        "Yeast_weak",
        "Yeast_strong",
    ],

    "N_sequences": [

        n_R1_random,
        n_R6_top,
        n_yeast_weak,
        n_yeast_strong,
    ],
})


# ============================================================
# OUTPUT SUMMARY
# ============================================================

# Four labelled 16 x 16 HRI matrices:
#
#     HRI_R1_random
#
#     HRI_R6_top
#
#     HRI_yeast_weak
#
#     HRI_yeast_strong
#
#
# Long-format plotting dataframe:
#
#     figure_2_22
#
#
# Sequence-set summary:
#
#     figure_2_22_sequence_sets
#
#
# Matrix ordering:
#
#     AA AT TA TT
#
#     AC AG CA CT GA GT TC TG
#
#     CC CG GC GG
#
#
# HRI:
#
#     positive
#         preferential spacing around multiples
#         of the full helical repeat
#
#     negative
#         preferential spacing around odd
#         multiples of half the helical repeat
#
#
# No plotting is performed.