

"""
Code 32 Figure 3-13 HRI and 10-mer cumulative score.py
=======================================================

WHAT THIS SCRIPT DOES
---------------------
Generates the data underlying Figure 3.13.

FIGURE 3.13a
------------
HRI heatmaps are calculated for:

    1. 10,000 sequences with the lowest 10-mer
       cumulative scores

    2. 10,000 randomly selected sequences

    3. 10,000 sequences with the highest 10-mer
       cumulative scores

The pooled-sequence HRI calculation follows:

    Code 17 Figure 2-22 HRI heatmaps.py


FIGURE 3.13b
------------
For each of the 100,000 random sequences, individual-
sequence HRI values are calculated.

The individual-sequence calculation follows the same
approach used in:

    Code 19 Figure 2-24 HRI contribution to intrinsic
    cyclisability.py

Three quantities are then calculated:

    Sum of 10 independent WW-WW HRI values
    Sum of 10 independent SS-SS HRI values
    Sum of 16 independent WW-SS HRI values

These are compared with the 10-mer cumulative score.


FIGURE 3.13c
------------
For every reverse-complement-collapsed 10-mer in the
SELEX enrichment table, the number of WW-SS dinucleotide
pairs separated by 4, 5 or 6 bp is calculated.

This is compared with the corresponding R6 versus R1
log2 enrichment value.


VARIABLES THAT MUST ALREADY EXIST
---------------------------------
random_sequences

    100,000 random 147-bp sequences generated by:

        Code 31 Figures 3-11 and 3-12 10-mer cumulative
        score sequence properties.py


tenmer_cumulative_score

    108-bp 10-mer cumulative score for those same
    100,000 sequences.

    Generated by Code 31.


df_enrichment_rc

    Reverse-complement-collapsed 10-mer enrichment table.

    Generated by:

        Code 20 Figure 2-25a 10-mer enrichment
        distribution.py


OTHER SCRIPTS THAT MUST BE RUN FIRST
------------------------------------
1. Code 20 Figure 2-25a 10-mer enrichment distribution.py

2. Code 31 Figures 3-11 and 3-12 10-mer cumulative
   score sequence properties.py


OUTPUTS
-------
figure_3_13a_HRI_matrices

    Dictionary containing HRI matrices for:

        Lowest
        Random
        Highest


figure_3_13b

    Individual-sequence data containing:

        10-mer cumulative score
        WW-WW HRI sum
        SS-SS HRI sum
        WW-SS HRI sum


figure_3_13b_correlations

    Pearson correlations with 10-mer cumulative score.


figure_3_13c

    Reverse-complement-collapsed 10-mer enrichment and
    number of WW-SS pairs separated by 4, 5 or 6 bp.


figure_3_13c_correlation

    Pearson correlation for Figure 3.13c.


NOTES
-----
No plotting is performed.
"""


import numpy as np
import pandas as pd

from scipy.stats import pearsonr


# ============================================================
# 1. Check required variables
# ============================================================

if "random_sequences" not in globals():

    raise RuntimeError(
        "random_sequences must already exist. "
        "Run Code 31 Figures 3-11 and 3-12 first."
    )


if "tenmer_cumulative_score" not in globals():

    raise RuntimeError(
        "tenmer_cumulative_score must already exist. "
        "Run Code 31 Figures 3-11 and 3-12 first."
    )


if "df_enrichment_rc" not in globals():

    raise RuntimeError(
        "df_enrichment_rc must already exist. "
        "Run Code 20 Figure 2-25a first."
    )


# ============================================================
# 2. Parameters
# ============================================================

N_RANDOM = 100000

VARIABLE_START = 17
VARIABLE_END = 130

VARIABLE_LENGTH = 113

N_DINUCLEOTIDE_STARTS = 112


WW = [
    "AA",
    "AT",
    "TA",
    "TT"
]


SS = [
    "CC",
    "CG",
    "GC",
    "GG"
]


DINUCLEOTIDE_ORDER = [

    "AA", "AT", "TA", "TT",

    "AC", "AG", "CA", "CT",
    "GA", "GT", "TC", "TG",

    "CC", "CG", "GC", "GG"
]


FULL_HELICAL_CENTRES = np.arange(
    10,
    111,
    10
)


HALF_HELICAL_CENTRES = np.arange(
    5,
    106,
    10
)


assert len(random_sequences) == N_RANDOM

assert len(tenmer_cumulative_score) == N_RANDOM


# ============================================================
# 3. Extract central 113-bp regions
# ============================================================

central_113 = [

    sequence[
        VARIABLE_START:
        VARIABLE_END
    ]

    for sequence in random_sequences
]


assert all(
    len(sequence) == VARIABLE_LENGTH
    for sequence in central_113
)


# ============================================================
# 4. Select lowest, random and highest score groups
# ============================================================

score_order = np.argsort(
    tenmer_cumulative_score
)


lowest_indices = score_order[
    :10000
]


highest_indices = score_order[
    -10000:
]


# Reproducible random control.

rng_hri = np.random.default_rng(
    42
)


random_indices = rng_hri.choice(

    N_RANDOM,

    size=10000,

    replace=False
)


figure_3_13a_groups = {

    "Lowest":
        lowest_indices,

    "Random":
        random_indices,

    "Highest":
        highest_indices
}


# ============================================================
# 5. Pair-count helper
# ============================================================

def count_pair_at_distance(
    sequences,
    dinucleotide_1,
    dinucleotide_2,
    distance
):

    """
    Count occurrences of an unordered dinucleotide pair
    separated by a given distance between dinucleotide
    start positions.

    For identical dinucleotides, each occurrence is
    counted once.

    For different dinucleotides, both orientations are
    included:

        NN1 ... NN2
        NN2 ... NN1
    """

    count = 0


    for sequence in sequences:

        for i in range(
            N_DINUCLEOTIDE_STARTS
            -
            distance
        ):

            left = sequence[
                i:
                i + 2
            ]

            right = sequence[
                i + distance:
                i + distance + 2
            ]


            if dinucleotide_1 == dinucleotide_2:

                if (
                    left == dinucleotide_1
                    and
                    right == dinucleotide_2
                ):

                    count += 1

            else:

                if (

                    (
                        left == dinucleotide_1
                        and
                        right == dinucleotide_2
                    )

                    or

                    (
                        left == dinucleotide_2
                        and
                        right == dinucleotide_1
                    )

                ):

                    count += 1


    return count


# ============================================================
# 6. Pooled rho(d)
# ============================================================

def pooled_rho(
    sequences,
    dinucleotide_1,
    dinucleotide_2
):

    """
    Calculate rho(d) across a pooled group of sequences.

    This follows the pooled HRI calculation used for the
    Figure 2.22 heatmaps.
    """

    N = len(
        sequences
    )


    rho = np.full(
        112,
        np.nan
    )


    for distance in range(
        1,
        112
    ):

        observed = count_pair_at_distance(

            sequences,

            dinucleotide_1,

            dinucleotide_2,

            distance
        )


        if dinucleotide_1 == dinucleotide_2:

            expected = (

                N

                *

                (
                    N_DINUCLEOTIDE_STARTS
                    -
                    distance
                )

                /

                256
            )

        else:

            expected = (

                N

                *

                (
                    N_DINUCLEOTIDE_STARTS
                    -
                    distance
                )

                /

                128
            )


        rho[
            distance
        ] = (

            observed

            /

            expected
        )


    return rho


# ============================================================
# 7. Convert rho(d) into HRI
# ============================================================

def hri_from_rho(
    rho
):

    """
    HRI = sum of maxima around integer helical repeats
          minus
          sum of maxima around half-integer repeats.

    Each maximum is taken within +/- 1 bp of the nominal
    centre.
    """

    full_values = []

    half_values = []


    for centre in FULL_HELICAL_CENTRES:

        values = rho[
            centre - 1:
            centre + 2
        ]


        full_values.append(
            np.nanmax(values)
        )


    for centre in HALF_HELICAL_CENTRES:

        values = rho[
            centre - 1:
            centre + 2
        ]


        half_values.append(
            np.nanmax(values)
        )


    return (

        np.sum(
            full_values
        )

        -

        np.sum(
            half_values
        )
    )


# ============================================================
# 8. Calculate one pooled HRI matrix
# ============================================================

def calculate_pooled_hri_matrix(
    sequences
):

    """
    Calculate the symmetric 16 x 16 pooled HRI matrix.
    """

    matrix = np.full(
        (16, 16),
        np.nan
    )


    for i, dinucleotide_1 in enumerate(
        DINUCLEOTIDE_ORDER
    ):

        for j in range(
            i,
            16
        ):

            dinucleotide_2 = (
                DINUCLEOTIDE_ORDER[j]
            )


            rho = pooled_rho(

                sequences,

                dinucleotide_1,

                dinucleotide_2
            )


            hri = hri_from_rho(
                rho
            )


            matrix[
                i,
                j
            ] = hri


            matrix[
                j,
                i
            ] = hri


    return matrix


# ============================================================
# 9. Figure 3.13a HRI heatmaps
# ============================================================

figure_3_13a_HRI_matrices = {}


for group_name, indices in (
    figure_3_13a_groups.items()
):

    print(
        "Calculating pooled HRI matrix:",
        group_name
    )


    group_sequences = [

        central_113[i]

        for i in indices
    ]


    matrix = calculate_pooled_hri_matrix(
        group_sequences
    )


    figure_3_13a_HRI_matrices[
        group_name
    ] = pd.DataFrame(

        matrix,

        index=DINUCLEOTIDE_ORDER,

        columns=DINUCLEOTIDE_ORDER
    )


# ============================================================
# 10. Individual-sequence rho(d)
# ============================================================

def individual_rho(
    sequence,
    dinucleotide_1,
    dinucleotide_2
):

    """
    Calculate rho(d) for one 113-bp sequence.

    This follows the individual-sequence HRI approach
    used in Code 19.
    """

    rho = np.full(
        112,
        np.nan
    )


    for distance in range(
        1,
        112
    ):

        observed = 0


        for i in range(
            N_DINUCLEOTIDE_STARTS
            -
            distance
        ):

            left = sequence[
                i:
                i + 2
            ]

            right = sequence[
                i + distance:
                i + distance + 2
            ]


            if dinucleotide_1 == dinucleotide_2:

                if (

                    left == dinucleotide_1

                    and

                    right == dinucleotide_2

                ):

                    observed += 1


            else:

                if (

                    (
                        left == dinucleotide_1
                        and
                        right == dinucleotide_2
                    )

                    or

                    (
                        left == dinucleotide_2
                        and
                        right == dinucleotide_1
                    )

                ):

                    observed += 1


        if dinucleotide_1 == dinucleotide_2:

            expected = (

                (
                    N_DINUCLEOTIDE_STARTS
                    -
                    distance
                )

                /

                256
            )

        else:

            expected = (

                (
                    N_DINUCLEOTIDE_STARTS
                    -
                    distance
                )

                /

                128
            )


        rho[
            distance
        ] = (

            observed

            /

            expected
        )


    return rho


# ============================================================
# 11. Individual HRI
# ============================================================

def individual_hri(
    sequence,
    dinucleotide_1,
    dinucleotide_2
):

    rho = individual_rho(

        sequence,

        dinucleotide_1,

        dinucleotide_2
    )


    return hri_from_rho(
        rho
    )


# ============================================================
# 12. Independent WW-WW, SS-SS and WW-SS pairs
# ============================================================

WW_WW_PAIRS = [

    (
        WW[i],
        WW[j]
    )

    for i in range(4)

    for j in range(
        i,
        4
    )
]


SS_SS_PAIRS = [

    (
        SS[i],
        SS[j]
    )

    for i in range(4)

    for j in range(
        i,
        4
    )
]


WW_SS_PAIRS = [

    (
        ww,
        ss
    )

    for ww in WW

    for ss in SS
]


assert len(
    WW_WW_PAIRS
) == 10


assert len(
    SS_SS_PAIRS
) == 10


assert len(
    WW_SS_PAIRS
) == 16


# ============================================================
# 13. Calculate summed individual HRI values
# ============================================================

# The calculation is deliberately written in terms of the
# same individual-pair HRI definition used above.
#
# This is computationally intensive for 100,000 sequences.


WW_WW_HRI_sum_10 = np.zeros(
    N_RANDOM
)


SS_SS_HRI_sum_10 = np.zeros(
    N_RANDOM
)


WW_SS_HRI_sum_16 = np.zeros(
    N_RANDOM
)


for sequence_index, sequence in enumerate(
    central_113
):

    if sequence_index % 1000 == 0:

        print(
            "Individual HRI:",
            sequence_index,
            "/",
            N_RANDOM
        )


    WW_WW_HRI_sum_10[
        sequence_index
    ] = np.sum([

        individual_hri(
            sequence,
            pair[0],
            pair[1]
        )

        for pair in WW_WW_PAIRS
    ])


    SS_SS_HRI_sum_10[
        sequence_index
    ] = np.sum([

        individual_hri(
            sequence,
            pair[0],
            pair[1]
        )

        for pair in SS_SS_PAIRS
    ])


    WW_SS_HRI_sum_16[
        sequence_index
    ] = np.sum([

        individual_hri(
            sequence,
            pair[0],
            pair[1]
        )

        for pair in WW_SS_PAIRS
    ])


# ============================================================
# 14. Figure 3.13b data
# ============================================================

figure_3_13b = pd.DataFrame({

    "Sequence":
        random_sequences,

    "Tenmer_cumulative_score":
        tenmer_cumulative_score,

    "WW_WW_HRI_sum_10":
        WW_WW_HRI_sum_10,

    "SS_SS_HRI_sum_10":
        SS_SS_HRI_sum_10,

    "WW_SS_HRI_sum_16":
        WW_SS_HRI_sum_16
})


# ============================================================
# 15. Figure 3.13b correlations
# ============================================================

def correlation(
    x,
    y
):

    x = np.asarray(
        x,
        dtype=float
    )

    y = np.asarray(
        y,
        dtype=float
    )


    valid = (

        np.isfinite(x)

        &

        np.isfinite(y)
    )


    r, p = pearsonr(

        x[valid],

        y[valid]
    )


    return (
        int(valid.sum()),
        r,
        p
    )


correlation_rows = []


for column, label in [

    (
        "WW_WW_HRI_sum_10",
        "WW-WW HRI sum"
    ),

    (
        "SS_SS_HRI_sum_10",
        "SS-SS HRI sum"
    ),

    (
        "WW_SS_HRI_sum_16",
        "WW-SS HRI sum"
    )
]:

    n, r, p = correlation(

        tenmer_cumulative_score,

        figure_3_13b[
            column
        ]
    )


    correlation_rows.append({

        "Property":
            label,

        "N":
            n,

        "Pearson_r":
            r,

        "P_value":
            p
    })


figure_3_13b_correlations = pd.DataFrame(
    correlation_rows
)


# ============================================================
# 16. Count WW-SS pairs in a 10-mer
# ============================================================

def count_ww_ss_pairs_4_to_6(
    kmer
):

    """
    Count WW-SS dinucleotide pairs whose dinucleotide
    start positions are separated by 4, 5 or 6 bp.

    Both orientations are included:

        WW ... SS

        SS ... WW
    """

    assert len(
        kmer
    ) == 10


    dinucleotides = [

        kmer[
            i:
            i + 2
        ]

        for i in range(9)
    ]


    count = 0


    for distance in [
        4,
        5,
        6
    ]:

        for i in range(
            9 - distance
        ):

            first = (
                dinucleotides[i]
            )

            second = (
                dinucleotides[
                    i + distance
                ]
            )


            if (

                (
                    first in WW
                    and
                    second in SS
                )

                or

                (
                    first in SS
                    and
                    second in WW
                )

            ):

                count += 1


    return count


# ============================================================
# 17. Figure 3.13c
# ============================================================

figure_3_13c = (
    df_enrichment_rc[
        [
            "kmer",
            "log2_enrichment"
        ]
    ]
    .copy()
)


figure_3_13c[
    "WW_SS_pairs_separation_4_to_6"
] = [

    count_ww_ss_pairs_4_to_6(
        str(kmer).upper()
    )

    for kmer in figure_3_13c[
        "kmer"
    ]
]


# ============================================================
# 18. Figure 3.13c correlation
# ============================================================

n_13c, r_13c, p_13c = correlation(

    figure_3_13c[
        "WW_SS_pairs_separation_4_to_6"
    ],

    figure_3_13c[
        "log2_enrichment"
    ]
)


figure_3_13c_correlation = pd.DataFrame({

    "N": [
        n_13c
    ],

    "Pearson_r": [
        r_13c
    ],

    "P_value": [
        p_13c
    ]
})


# ============================================================
# 19. Report results
# ============================================================

print(
    "\nFigure 3.13a HRI matrices calculated:"
)


for name in figure_3_13a_HRI_matrices:

    print(
        "   ",
        name
    )


print(
    "\nFigure 3.13b correlations:"
)


print(
    figure_3_13b_correlations
)


print(
    "\nFigure 3.13c:"
)


print(
    f"N = {n_13c}"
)


print(
    f"Pearson r = {r_13c:.4f}"
)


print(
    f"P = {p_13c:.4g}"
)


# ============================================================
# OUTPUT SUMMARY
# ============================================================

# ============================================================
# FIGURE 3.13a
# ============================================================
#
# Sequence indices:
#
#     lowest_indices
#     random_indices
#     highest_indices
#
#
# HRI heatmaps:
#
#     figure_3_13a_HRI_matrices["Lowest"]
#     figure_3_13a_HRI_matrices["Random"]
#     figure_3_13a_HRI_matrices["Highest"]
#
#
# ============================================================
# FIGURE 3.13b
# ============================================================
#
# Sequence-level HRI sums:
#
#     figure_3_13b
#
#
# Correlations:
#
#     figure_3_13b_correlations
#
#
# ============================================================
# FIGURE 3.13c
# ============================================================
#
# 10-mer WW-SS pair counts and enrichment:
#
#     figure_3_13c
#
#
# Correlation:
#
#     figure_3_13c_correlation
#
#
# No plotting is performed.