
"""
Code 21 Figure 2-26 10-mer GC and poly dAdT analysis.py
========================================================

WHAT THIS SCRIPT DOES
---------------------
Generates the data underlying Figure 2.26.

Figure 2.26 examines the relationship between SELEX
10-mer enrichment and two simple sequence features:

    1. GC content

    2. poly(dA:dT) content

The analysis uses the reverse-complement-collapsed
10-mer enrichment table generated in:

    Code 20 Figure 2-25a 10-mer enrichment distribution.py

For each reverse-complement-collapsed 10-mer, the script
calculates its GC fraction and the fraction of bases
belonging to poly(dA:dT) tracts.

These quantities are compared with the R6-versus-R1
log2 enrichment of the 10-mer.


FIGURE 2.26
-----------
Left panel:

    log2 enrichment as a function of GC content.

Right panel:

    log2 enrichment as a function of the fraction of
    bases belonging to poly(dA:dT) tracts.


GC CONTENT
----------
GC content is calculated as the fraction of the 10 bases
that are G or C:

    GC fraction =
        number of G or C bases / 10

Possible values are:

    0.0, 0.1, 0.2, ..., 1.0


POLY(dA:dT) CONTENT
-------------------
A poly(dA:dT) tract is defined as an uninterrupted run
of at least 5 consecutive A bases or at least 5
consecutive T bases.

For each 10-mer, the poly(dA:dT) fraction is calculated
as:

    number of bases belonging to qualifying A/T tracts
    --------------------------------------------------
                         10

For example:

    AAAAAAAAAA

        Poly_dAdT_fraction = 1.0

    AAAAATCGCG

        Poly_dAdT_fraction = 0.5

    AAAATTTTGC

        Poly_dAdT_fraction = 0.0

because neither uninterrupted run reaches 5 bases.


INPUT
-----
df_enrichment_rc

The reverse-complement-collapsed enrichment table
generated by:

    Code 20 Figure 2-25a 10-mer enrichment distribution.py

In Code 20, overlapping 10-mers are first counted in
their observed orientation using CPM weighting. Counts
for each 10-mer and its reverse complement are then
combined before frequencies and R6-versus-R1 enrichment
are calculated.

Each reverse-complement pair is therefore represented
once in df_enrichment_rc.

The complete 10-mer sequence space contains 524,800
reverse-complement classes.

df_enrichment_rc contains:

    kmer
    freq_R1
    freq_R6
    enrichment
    log2_enrichment


OTHER SCRIPTS THAT MUST BE RUN FIRST
------------------------------------
Code 20 Figure 2-25a 10-mer enrichment distribution.py


OUTPUTS
-------
figure_2_26

    Complete per-10-mer table containing:

        kmer
        log2_enrichment
        GC_count
        GC_fraction
        Poly_dAdT_bases
        Poly_dAdT_fraction


figure_2_26_gc

    Data underlying the left panel:

        GC_fraction
            vs
        log2_enrichment


figure_2_26_poly_dAdT

    Data underlying the right panel:

        Poly_dAdT_fraction
            vs
        log2_enrichment


NOTES
-----
GC fraction and poly(dA:dT) fraction are unchanged by
reverse complementation. Therefore, either member of a
reverse-complement pair has the same value for both
sequence features.

No plotting is performed.
"""

import numpy as np
import pandas as pd


# ============================================================
# 1. Check reverse-complement-collapsed enrichment table
# ============================================================

if "df_enrichment_rc" not in globals():

    raise RuntimeError(

        "df_enrichment_rc is not defined. "
        "The reverse-complement-collapsed 10-mer "
        "enrichment table must be generated first."
    )


required_columns = {

    "kmer",

    "log2_enrichment",
}


missing_columns = (

    required_columns

    -

    set(
        df_enrichment_rc.columns
    )
)


if missing_columns:

    raise ValueError(

        "df_enrichment_rc is missing required columns: "
        f"{missing_columns}"
    )


# ============================================================
# 2. GC content
# ============================================================

def gc_count(sequence):

    sequence = str(sequence).upper()

    return sum(
        base in {"G", "C"}
        for base in sequence
    )


# ============================================================
# 3. poly(dA:dT) content
# ============================================================

def poly_dAdT_base_count(
    sequence,
    minimum_run=5
):

    """
    Count bases belonging to uninterrupted runs of
    at least 5 consecutive A bases or at least
    5 consecutive T bases.
    """

    sequence = str(sequence).upper()

    n = len(sequence)

    in_poly_tract = np.zeros(
        n,
        dtype=bool
    )

    i = 0

    while i < n:

        base = sequence[i]

        if base not in {"A", "T"}:

            i += 1
            continue


        j = i + 1

        while (
            j < n
            and
            sequence[j] == base
        ):

            j += 1


        run_length = j - i


        if run_length >= minimum_run:

            in_poly_tract[i:j] = True


        i = j


    return int(
        np.sum(in_poly_tract)
    )


# ============================================================
# 4. Construct Figure 2.26 table
# ============================================================

figure_2_26 = (

    df_enrichment_rc

    .copy()
)


figure_2_26["kmer"] = (

    figure_2_26["kmer"]

    .astype(str)

    .str.upper()
)


# Check that all entries are 10-mers.

if not (
    figure_2_26["kmer"].str.len() == 10
).all():

    raise ValueError(
        "Figure 2.26 requires 10-bp sequences."
    )


# ============================================================
# 5. GC content
# ============================================================

figure_2_26["GC_count"] = (

    figure_2_26["kmer"]

    .apply(
        gc_count
    )
)


figure_2_26["GC_fraction"] = (

    figure_2_26["GC_count"]

    /

    10.0
)


# ============================================================
# 6. poly(dA:dT) content
# ============================================================

figure_2_26["Poly_dAdT_bases"] = (

    figure_2_26["kmer"]

    .apply(
        poly_dAdT_base_count
    )
)


figure_2_26["Poly_dAdT_fraction"] = (

    figure_2_26["Poly_dAdT_bases"]

    /

    10.0
)


# ============================================================
# 7. Figure 2.26 left panel
# ============================================================

figure_2_26_gc = (

    figure_2_26[
        [
            "kmer",
            "GC_count",
            "GC_fraction",
            "log2_enrichment",
        ]
    ]

    .copy()
)


# ============================================================
# 8. Figure 2.26 right panel
# ============================================================

figure_2_26_poly_dAdT = (

    figure_2_26[
        [
            "kmer",
            "Poly_dAdT_bases",
            "Poly_dAdT_fraction",
            "log2_enrichment",
        ]
    ]

    .copy()
)


# ============================================================
# 9. Useful checks
# ============================================================

print(
    "Number of reverse-complement-collapsed 10-mers:",
    len(figure_2_26)
)


print(
    "\nGC fractions:"
)


print(

    figure_2_26_gc[
        "GC_fraction"
    ]

    .value_counts()

    .sort_index()
)


print(
    "\npoly(dA:dT) fractions:"
)


print(

    figure_2_26_poly_dAdT[
        "Poly_dAdT_fraction"
    ]

    .value_counts()

    .sort_index()
)


# ============================================================
# OUTPUT SUMMARY
# ============================================================

# Complete Figure 2.26 data:
#
#     figure_2_26
#
#
# Left panel:
#
#     figure_2_26_gc
#
# x:
#
#     GC_fraction
#
# y:
#
#     log2_enrichment
#
#
# Right panel:
#
#     figure_2_26_poly_dAdT
#
# x:
#
#     Poly_dAdT_fraction
#
# y:
#
#     log2_enrichment
#
#
# poly(dA:dT) fraction is the fraction of the 10 bases
# belonging to uninterrupted runs of at least 5 A bases
# or at least 5 T bases.
#
#
# The input table is reverse-complement collapsed:
#
#     524,800 possible reverse-complement classes
#
#
# No plotting is performed.