

"""
Code 22 Figure 2-27 10-mer enrichment and yeast nucleosome occurrence.py
========================================================================

WHAT THIS SCRIPT DOES
---------------------
Generates the data underlying Figure 2.27.

Figure 2.27 examines the relationship between SELEX
10-mer enrichment and the occurrence of the same 10-mers
within native yeast nucleosomal DNA.

The analysis uses the reverse-complement-collapsed
10-mer enrichment table generated in:

    Code 20 Figure 2-25a 10-mer enrichment distribution.py

For every reverse-complement-collapsed 10-mer, the script
calculates its nucleosomal occurrence in the 147-bp DNA
sequences centred on the dyads of the 67,539 mapped
native yeast nucleosomes.

Nucleosomal occurrence is defined as:

    the total number of times a given 10-mer is observed
    within the 147-bp sequences surrounding the mapped
    yeast nucleosome dyads.

The resulting occurrence is compared with the
R6-versus-R1 log2 enrichment of the same 10-mer.


10-MER COUNTING
---------------
Each 147-bp native nucleosomal sequence contains:

    147 - 10 + 1 = 138

overlapping 10-mers.

Every occurrence is counted.

For consistency with the SELEX enrichment table, each
observed yeast 10-mer is collapsed with its reverse
complement using the same canonical representation as
Code 20.

For a 10-mer:

    canonical kmer =
        lexicographically smaller of

            kmer

        and

            reverse_complement(kmer)

Thus a 10-mer and its reverse complement contribute to
the same nucleosomal-occurrence count.


INPUT
-----
df_enrichment_rc

The reverse-complement-collapsed 10-mer enrichment table
generated by:

    Code 20 Figure 2-25a 10-mer enrichment distribution.py

The table contains:

    kmer
    freq_R1
    freq_R6
    enrichment
    log2_enrichment


native_nucleosomes

The native yeast nucleosome dataframe generated by:

    Code 5 Native yeast nucleosomal sequences.py

It must contain a column:

    Sequence

containing the 147-bp sequence centred on each mapped
nucleosome dyad.


OTHER SCRIPTS THAT MUST BE RUN FIRST
------------------------------------
Code 5 Native yeast nucleosomal sequences.py

Code 20 Figure 2-25a 10-mer enrichment distribution.py


OUTPUTS
-------
figure_2_27

    Complete table containing:

        kmer
        log2_enrichment
        Nucleosomal_occurrence


figure_2_27_correlation

    Summary containing the Pearson correlation
    coefficient and p-value between:

        log2_enrichment

    and

        Nucleosomal_occurrence


No plotting is performed.
"""


import numpy as np
import pandas as pd

from collections import defaultdict

from scipy.stats import pearsonr


# ============================================================
# 1. Parameters
# ============================================================

K = 10

NUCLEOSOME_LENGTH = 147


# ============================================================
# 2. Check required inputs
# ============================================================

if "df_enrichment_rc" not in globals():

    raise RuntimeError(

        "df_enrichment_rc is not defined. Run "
        "'Code 20 Figure 2-25a 10-mer enrichment "
        "distribution.py' first."
    )


if "native_nucleosomes" not in globals():

    raise RuntimeError(

        "native_nucleosomes is not defined. Run "
        "'Code 5 Native yeast nucleosomal sequences.py' "
        "first."
    )


required_enrichment_columns = {

    "kmer",

    "log2_enrichment",
}


missing_columns = (

    required_enrichment_columns

    -

    set(
        df_enrichment_rc.columns
    )
)


if missing_columns:

    raise ValueError(

        "df_enrichment_rc is missing required columns: "
        f"{missing_columns}"
    )


if "Sequence" not in native_nucleosomes.columns:

    raise ValueError(

        "native_nucleosomes does not contain "
        "a Sequence column."
    )


# ============================================================
# 3. Reverse-complement functions
# ============================================================

COMPLEMENT = str.maketrans(

    "ACGT",

    "TGCA"
)


def reverse_complement(
    sequence
):

    """
    Return the reverse complement of a DNA sequence.
    """

    return (

        sequence

        .translate(
            COMPLEMENT
        )

        [::-1]
    )


def canonical_kmer(
    kmer
):

    """
    Return the canonical representative of a k-mer
    and its reverse complement.

    This is the same convention used in Code 20.
    """

    rc = reverse_complement(
        kmer
    )


    return min(
        kmer,
        rc
    )


# ============================================================
# 4. Count 10-mers in native yeast nucleosomal DNA
# ============================================================

def count_native_nucleosome_kmers(
    sequences
):

    """
    Count reverse-complement-collapsed 10-mer
    occurrences across native 147-bp nucleosomal
    sequences.

    Every overlapping occurrence is counted.
    """

    counts = defaultdict(
        int
    )


    n_valid_sequences = 0

    n_skipped_sequences = 0


    for sequence in sequences:

        sequence = str(
            sequence
        ).upper()


        # ----------------------------------------------------
        # Ignore sequences containing ambiguous bases
        # ----------------------------------------------------

        if "N" in sequence:

            n_skipped_sequences += 1

            continue


        # ----------------------------------------------------
        # Only complete 147-bp nucleosomal sequences
        # contribute
        # ----------------------------------------------------

        if len(
            sequence
        ) != NUCLEOSOME_LENGTH:

            n_skipped_sequences += 1

            continue


        n_valid_sequences += 1


        # ----------------------------------------------------
        # Extract all overlapping 10-mers
        #
        # 147 - 10 + 1 = 138
        # ----------------------------------------------------

        for i in range(

            len(sequence)
            -
            K
            +
            1
        ):

            kmer = sequence[
                i:
                i + K
            ]


            canonical = canonical_kmer(
                kmer
            )


            counts[
                canonical
            ] += 1


    return (
        counts,
        n_valid_sequences,
        n_skipped_sequences
    )


# ============================================================
# 5. Calculate native nucleosomal occurrence
# ============================================================

print(
    "Counting 10-mers in native yeast nucleosomes..."
)


(
    native_kmer_counts,
    n_valid_native_sequences,
    n_skipped_native_sequences

) = count_native_nucleosome_kmers(

    native_nucleosomes[
        "Sequence"
    ]
)


# ============================================================
# 6. Construct Figure 2.27 table
# ============================================================

figure_2_27 = (

    df_enrichment_rc[
        [
            "kmer",
            "log2_enrichment",
        ]
    ]

    .copy()
)


figure_2_27[
    "kmer"
] = (

    figure_2_27[
        "kmer"
    ]

    .astype(str)

    .str.upper()
)


# ------------------------------------------------------------
# Ensure that the enrichment-table sequences use the same
# canonical representation as the native counts.
# ------------------------------------------------------------

figure_2_27[
    "kmer"
] = (

    figure_2_27[
        "kmer"
    ]

    .apply(
        canonical_kmer
    )
)


# ------------------------------------------------------------
# Native nucleosomal occurrence
# ------------------------------------------------------------

figure_2_27[
    "Nucleosomal_occurrence"
] = (

    figure_2_27[
        "kmer"
    ]

    .map(
        native_kmer_counts
    )

    .fillna(
        0
    )

    .astype(
        int
    )
)


# ============================================================
# 7. Pearson correlation
# ============================================================

valid = (

    np.isfinite(

        figure_2_27[
            "log2_enrichment"
        ]
    )

    &

    np.isfinite(

        figure_2_27[
            "Nucleosomal_occurrence"
        ]
    )
)


x = (

    figure_2_27

    .loc[
        valid,
        "log2_enrichment"
    ]

    .to_numpy(
        dtype=float
    )
)


y = (

    figure_2_27

    .loc[
        valid,
        "Nucleosomal_occurrence"
    ]

    .to_numpy(
        dtype=float
    )
)


pearson_r, pearson_p = pearsonr(
    x,
    y
)


# ============================================================
# 8. Correlation summary
# ============================================================

figure_2_27_correlation = pd.DataFrame(

    {

        "N_10mers": [
            len(x)
        ],

        "Pearson_r": [
            pearson_r
        ],

        "Pearson_p": [
            pearson_p
        ],
    }
)


# ============================================================
# 9. Useful checks
# ============================================================

print(
    "\nNative nucleosome sequences supplied:",
    len(
        native_nucleosomes
    )
)


print(
    "Valid 147-bp native sequences:",
    n_valid_native_sequences
)


print(
    "Skipped native sequences:",
    n_skipped_native_sequences
)


print(
    "\nExpected mapped yeast nucleosomes:",
    67539
)


print(
    "\n10-mers per complete nucleosome:",
    NUCLEOSOME_LENGTH - K + 1
)


expected_total_occurrences = (

    n_valid_native_sequences

    *

    (
        NUCLEOSOME_LENGTH
        -
        K
        +
        1
    )
)


observed_total_occurrences = sum(

    native_kmer_counts.values()
)


print(
    "Expected total 10-mer occurrences:",
    expected_total_occurrences
)


print(
    "Observed total 10-mer occurrences:",
    observed_total_occurrences
)


if (
    observed_total_occurrences
    !=
    expected_total_occurrences
):

    print(
        "WARNING: total 10-mer occurrence count "
        "does not match expectation."
    )


# ============================================================
# 10. Correlation result
# ============================================================

print(
    "\nFigure 2.27 correlation:"
)


print(

    figure_2_27_correlation

    .to_string(
        index=False
    )
)


# ============================================================
# OUTPUT SUMMARY
# ============================================================

# Figure 2.27 data:
#
#     figure_2_27
#
# Columns:
#
#     kmer
#     log2_enrichment
#     Nucleosomal_occurrence
#
#
# Nucleosomal occurrence is:
#
#     the number of times the reverse-complement-
#     collapsed 10-mer occurs within the 147-bp
#     sequences centred on the mapped native yeast
#     nucleosome dyads.
#
#
# Every complete 147-bp sequence contributes:
#
#     138 overlapping 10-mers
#
#
# A 10-mer and its reverse complement are counted
# together using the same canonical representation
# as Code 20.
#
#
# Correlation summary:
#
#     figure_2_27_correlation
#
# contains:
#
#     N_10mers
#     Pearson_r
#     Pearson_p
#
#
# The relationship plotted in Figure 2.27 is:
#
#     x = log2_enrichment
#
#     y = Nucleosomal_occurrence
#
#
# No plotting is performed.