

"""
Code 30 Figure 3-9 10-mer cumulative score and NFP.py
======================================================

WHAT THIS SCRIPT DOES
---------------------
Generates the data underlying Figure 3.9.

For each of the 2,000 sequences in the competitive
nucleosome reconstitution library, a 10-mer cumulative
score is calculated over the central 113-bp variable
region.

The central 113 bp contains:

    113 - 10 + 1 = 104

overlapping 10-mers.

Each 10-mer is converted to its reverse-complement-
collapsed canonical form and assigned the corresponding
R6 versus R1 log2 enrichment value.

The 10-mer cumulative score is the sum of these 104
log2 enrichment values.

The cumulative score is then compared with experimentally
measured nucleosome formation propensity (NFP).


VARIABLES THAT MUST ALREADY EXIST
---------------------------------
df_enrichment_rc

    Reverse-complement-collapsed 10-mer enrichment table
    containing:

        kmer
        freq_R1
        freq_R6
        enrichment
        log2_enrichment

    This is generated by:

        Code 20 Figure 2-25a 10-mer enrichment distribution.py


canonical_kmer

    Function that converts a 10-mer to the canonical
    representative of itself and its reverse complement.

    This is also defined by:

        Code 20 Figure 2-25a 10-mer enrichment distribution.py


seq

    Ordered list containing the 2,000 experimental
    sequences in the competitive nucleosome
    reconstitution library.

    This is generated by:

        Code 26 Figure 3-5 nucleosome formation propensity
        by sequence group.py


NFP

    Experimentally measured nucleosome formation
    propensity for the same 2,000 sequences.

    NFP is calculated as:

        ln[(A1 + 0.01) / (A2 (Free) + 0.01)]

    This is generated by:

        Code 26 Figure 3-5 nucleosome formation propensity
        by sequence group.py


FUNCTIONS THAT MUST ALREADY EXIST
---------------------------------
canonical_kmer


OTHER SCRIPTS THAT MUST BE RUN FIRST
------------------------------------
1. Code 20 Figure 2-25a 10-mer enrichment distribution.py

2. Code 26 Figure 3-5 nucleosome formation propensity
   by sequence group.py


OUTPUTS
-------
tenmer_score_dict

    Dictionary mapping each reverse-complement-collapsed
    10-mer to its R6 versus R1 log2 enrichment value.


tenmer_cumulative_score

    10-mer cumulative score for each of the 2,000
    experimental sequences.


figure_3_9

    DataFrame containing:

        Library_position
        Sequence
        NFP
        Tenmer_cumulative_score
        Plot_class


figure_3_9_correlation

    Pearson correlation coefficient and p value.


figure_3_9_fit

    Parameters of the best-fit linear relationship.


figure_3_9_fit_line

    x and y values for plotting the best-fit line.


SEQUENCE REGION
---------------
Figure 3.9 uses the complete central 113-bp variable
region:

    sequence[17:130]

This contains 104 overlapping 10-mers.

The optimized 108-bp summation region is analysed
separately in Figure 3.10.


PLOT CLASSES
------------
Library positions 1-200:

    SELEX

Library position 801:

    Widom 601

All remaining sequences:

    Other


NOTES
-----
No plotting is performed.
"""


import numpy as np
import pandas as pd

from scipy.stats import pearsonr
from scipy.stats import linregress


# ============================================================
# 1. Parameters
# ============================================================

N_SEQUENCES = 2000

SEQUENCE_LENGTH = 147

TRIM_LEFT = 17

TRIM_RIGHT = 17

VARIABLE_LENGTH = 113

K = 10

N_TENMERS = (
    VARIABLE_LENGTH
    -
    K
    +
    1
)  # 104


# ============================================================
# 2. Check required variables and functions
# ============================================================

if "df_enrichment_rc" not in globals():

    raise RuntimeError(
        "df_enrichment_rc must already exist. "
        "Run Code 20 Figure 2-25a 10-mer enrichment "
        "distribution.py first."
    )


if "canonical_kmer" not in globals():

    raise RuntimeError(
        "canonical_kmer must already exist. "
        "Run Code 20 Figure 2-25a 10-mer enrichment "
        "distribution.py first."
    )


if "seq" not in globals():

    raise RuntimeError(
        "seq must already exist. "
        "Run Code 26 Figure 3-5 nucleosome formation "
        "propensity by sequence group.py first."
    )


if "NFP" not in globals():

    raise RuntimeError(
        "NFP must already exist. "
        "Run Code 26 Figure 3-5 nucleosome formation "
        "propensity by sequence group.py first."
    )


# ============================================================
# 3. Check the 10-mer enrichment table
# ============================================================

required_columns = [
    "kmer",
    "log2_enrichment",
]


for column in required_columns:

    if column not in df_enrichment_rc.columns:

        raise ValueError(
            f"df_enrichment_rc must contain "
            f"the column '{column}'."
        )


# ============================================================
# 4. Check the experimental sequences and NFP values
# ============================================================

seq = [
    str(sequence).upper()
    for sequence in seq
]


NFP = np.asarray(
    NFP,
    dtype=float
)


assert len(seq) == N_SEQUENCES

assert len(NFP) == N_SEQUENCES


assert all(
    len(sequence) == SEQUENCE_LENGTH
    for sequence in seq
)


assert all(
    set(sequence).issubset(
        {"A", "C", "G", "T"}
    )
    for sequence in seq
)


# ============================================================
# 5. Construct the 10-mer enrichment lookup table
# ============================================================

# df_enrichment_rc has already been reverse-complement
# collapsed in Code 20.
#
# Therefore each canonical 10-mer maps directly to its
# R6 versus R1 log2 enrichment value.


tenmer_score_dict = dict(

    zip(

        df_enrichment_rc[
            "kmer"
        ],

        df_enrichment_rc[
            "log2_enrichment"
        ]
    )
)


print(
    "Number of 10-mer classes in score table:",
    len(
        tenmer_score_dict
    )
)


# ============================================================
# 6. Score one 10-mer
# ============================================================

def get_10mer_score(
    kmer
):

    """
    Return the R6 versus R1 log2 enrichment value of
    a 10-mer.

    The 10-mer is first converted to the same canonical
    reverse-complement representation used in Code 20.
    """

    canonical = canonical_kmer(
        kmer
    )


    if canonical not in tenmer_score_dict:

        raise KeyError(
            f"10-mer '{kmer}' "
            f"(canonical form '{canonical}') "
            "is not present in df_enrichment_rc."
        )


    return tenmer_score_dict[
        canonical
    ]


# ============================================================
# 7. Calculate the 10-mer cumulative score of one sequence
# ============================================================

def compute_10mer_cumulative_score(
    sequence
):

    """
    Calculate the 10-mer cumulative score over the
    complete central 113-bp variable region.

    A 113-bp sequence contains 104 overlapping 10-mers.

    The cumulative score is the sum of their R6 versus
    R1 log2 enrichment values.
    """

    central = sequence[

        TRIM_LEFT:

        SEQUENCE_LENGTH
        -
        TRIM_RIGHT
    ]


    assert len(
        central
    ) == VARIABLE_LENGTH


    score = 0.0


    for i in range(
        N_TENMERS
    ):

        kmer = central[
            i:
            i + K
        ]


        score += get_10mer_score(
            kmer
        )


    return score


# ============================================================
# 8. Calculate scores for all 2,000 sequences
# ============================================================

tenmer_cumulative_score = np.asarray([

    compute_10mer_cumulative_score(
        sequence
    )

    for sequence in seq

])


assert len(
    tenmer_cumulative_score
) == N_SEQUENCES


# ============================================================
# 9. Define sequence classes used in Figure 3.9
# ============================================================

plot_class = np.full(
    N_SEQUENCES,
    "Other",
    dtype=object
)


# Library positions 1-200:
# SELEX-enriched sequences.

plot_class[
    0:200
] = "SELEX"


# Library position 801:
# Widom 601.

plot_class[
    800
] = "Widom 601"


# ============================================================
# 10. Construct Figure 3.9 data
# ============================================================

figure_3_9 = pd.DataFrame({

    "Library_position":
        np.arange(
            1,
            N_SEQUENCES + 1
        ),

    "Sequence":
        seq,

    "NFP":
        NFP,

    "Tenmer_cumulative_score":
        tenmer_cumulative_score,

    "Plot_class":
        plot_class
})


# ============================================================
# 11. Retain finite values
# ============================================================

valid = (

    np.isfinite(
        tenmer_cumulative_score
    )

    &

    np.isfinite(
        NFP
    )
)


# ============================================================
# 12. Pearson correlation
# ============================================================

r_10mer, p_10mer = pearsonr(

    tenmer_cumulative_score[
        valid
    ],

    NFP[
        valid
    ]
)


figure_3_9_correlation = pd.DataFrame({

    "N": [
        int(
            valid.sum()
        )
    ],

    "Pearson_r": [
        r_10mer
    ],

    "P_value": [
        p_10mer
    ]
})


# ============================================================
# 13. Best-fit linear relationship
# ============================================================

fit = linregress(

    tenmer_cumulative_score[
        valid
    ],

    NFP[
        valid
    ]
)


figure_3_9_fit = pd.DataFrame({

    "Slope": [
        fit.slope
    ],

    "Intercept": [
        fit.intercept
    ],

    "Pearson_r": [
        fit.rvalue
    ],

    "P_value": [
        fit.pvalue
    ],

    "Standard_error": [
        fit.stderr
    ]
})


# ============================================================
# 14. Data for the best-fit line
# ============================================================

figure_3_9_fit_x = np.linspace(

    np.min(
        tenmer_cumulative_score[
            valid
        ]
    ),

    np.max(
        tenmer_cumulative_score[
            valid
        ]
    ),

    200
)


figure_3_9_fit_y = (

    fit.intercept

    +

    fit.slope
    *
    figure_3_9_fit_x
)


figure_3_9_fit_line = pd.DataFrame({

    "Tenmer_cumulative_score":
        figure_3_9_fit_x,

    "Fitted_NFP":
        figure_3_9_fit_y
})


# ============================================================
# 15. Useful plotting subsets
# ============================================================

figure_3_9_SELEX = (

    figure_3_9[

        figure_3_9[
            "Plot_class"
        ]
        ==
        "SELEX"
    ]

    .copy()
)


figure_3_9_Widom601 = (

    figure_3_9[

        figure_3_9[
            "Plot_class"
        ]
        ==
        "Widom 601"
    ]

    .copy()
)


figure_3_9_other = (

    figure_3_9[

        figure_3_9[
            "Plot_class"
        ]
        ==
        "Other"
    ]

    .copy()
)


# ============================================================
# 16. Final checks
# ============================================================

assert len(
    figure_3_9
) == 2000


assert len(
    figure_3_9_SELEX
) == 200


assert len(
    figure_3_9_Widom601
) == 1


assert len(
    figure_3_9_other
) == 1799


# ============================================================
# 17. Report results
# ============================================================

print(
    "\nFigure 3.9"
)


print(
    "10-mer cumulative score versus measured NFP"
)


print(
    "\nSummation region:",
    VARIABLE_LENGTH,
    "bp"
)


print(
    "10-mers per sequence:",
    N_TENMERS
)


print(
    "\nN =",
    valid.sum()
)


print(
    f"Pearson r = {r_10mer:.4f}"
)


print(
    f"P = {p_10mer:.4g}"
)


print(
    "\nBest-fit relationship:"
)


print(
    f"NFP = {fit.slope:.6f} "
    f"* 10-mer cumulative score "
    f"+ {fit.intercept:.6f}"
)


# ============================================================
# OUTPUT SUMMARY
# ============================================================

# Lookup dictionary derived directly from
# df_enrichment_rc:
#
#     tenmer_score_dict
#
#
# 10-mer cumulative score of each sequence:
#
#     tenmer_cumulative_score
#
#
# Complete Figure 3.9 data:
#
#     figure_3_9
#
#
# Pearson correlation:
#
#     figure_3_9_correlation
#
#
# Best-fit relationship:
#
#     figure_3_9_fit
#
#
# Data for the best-fit line:
#
#     figure_3_9_fit_line
#
#
# Plotting subsets:
#
#     figure_3_9_SELEX
#     figure_3_9_Widom601
#     figure_3_9_other
#
#
# No plotting is performed.